buildscript {
    repositories {
        mavenLocal()
        mavenCentral() 
        maven { url uri('https://maven.openflexo.org/artifactory/openflexo-deps/') }
    }
    dependencies {
        classpath group: 'org.openflexo', name: 'buildplugin', version: '0.3'
        classpath group: 'org.openflexo', name: 'buildconfig', version: '3.0'
        classpath 'org.openflexo:gradle-sablecc-plugin:[1.3.0,)'
        // implementation 'org.alloytools:alloy:6.3.0-SNAPSHOT'
        // classpath group: 'org.alloytools', name: 'org.alloytools.alloy.application', version:'6.3.0-SNAPSHOT'
        // compile "org.alloytools:org.alloytools.alloy.application:6.3.0-SNAPSHOT"
    }
}

version = "3.0"
apply plugin: 'org.openflexo.buildconfig'
