dependencies {
    // openflexo dep
    implementation flexoP2PP();
    implementation project(':flexo-foundation')
    // external dep

    // testing dep
    // testImplementation project(':flexo-foundation-test')
    testImplementation project(':flexo-test-resources')
}

apply plugin: 'sablecc'

sourceSets {
    main {
        java {
            srcDir("$buildDir/generated-sources/sablecc/main")
        }
    }
}

task printBuildDir {
    doLast {
        println "buildDir = " + buildDir
    }
}

def generateGrammarSourceTask = tasks.named("generateGrammarSource")

// TODO does it imply that runnning the task "processResources" from gradle will requires the task "generateGrammarSource" ? a regex of it didn't produce results
// We explicity declare a dependence between those two tasks
tasks.named("processResources") {
    dependsOn(generateGrammarSourceTask)
}

tasks.register("printSourceSets") {
    doLast {
        sourceSets.each { set ->
            println "SourceSet: " + set.name
            println "  java.srcDirs = " + set.java.srcDirs
            println "  allSource.srcDirs = " + set.allSource.srcDirs
        }
    }
}

//TODO why is there no "test" block configured in this build script and the presence of a "test" folder ?

/*
I would like to add "

test {
    debugOptions {
        enabled = true" }
    }
or 

test {
    debug true
}
*/
