/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

@SuppressWarnings("nls")
public final class AAbstractPropertyInnerConceptDecl extends PInnerConceptDecl {
    private final LinkedList<PAnnotation> _annotations_ = new LinkedList<PAnnotation>();
    private PVisibility _visibility_;
    private TKwAbstract _kwAbstract_;
    private PType _type_;
    private PVariableDeclarator _variableDeclarator_;
    private TSemi _semi_;

    public AAbstractPropertyInnerConceptDecl() {
        // Constructor
    }

    public AAbstractPropertyInnerConceptDecl(
            @SuppressWarnings("hiding") List<?> _annotations_,
            @SuppressWarnings("hiding") PVisibility _visibility_,
            @SuppressWarnings("hiding") TKwAbstract _kwAbstract_,
            @SuppressWarnings("hiding") PType _type_,
            @SuppressWarnings("hiding") PVariableDeclarator _variableDeclarator_,
            @SuppressWarnings("hiding") TSemi _semi_) {
        // Constructor
        setAnnotations(_annotations_);

        setVisibility(_visibility_);

        setKwAbstract(_kwAbstract_);

        setType(_type_);

        setVariableDeclarator(_variableDeclarator_);

        setSemi(_semi_);

    }

    @Override
    public Object clone() {
        return new AAbstractPropertyInnerConceptDecl(
                cloneList(this._annotations_),
                cloneNode(this._visibility_),
                cloneNode(this._kwAbstract_),
                cloneNode(this._type_),
                cloneNode(this._variableDeclarator_),
                cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAAbstractPropertyInnerConceptDecl(this);
    }

    public LinkedList<PAnnotation> getAnnotations() {
        return this._annotations_;
    }

    public void setAnnotations(List<?> list) {
        for (PAnnotation e : this._annotations_) {
            e.parent(null);
        }
        this._annotations_.clear();

        for (Object obj_e : list) {
            PAnnotation e = (PAnnotation) obj_e;
            if (e.parent() != null) {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._annotations_.add(e);
        }
    }

    public PVisibility getVisibility() {
        return this._visibility_;
    }

    public void setVisibility(PVisibility node) {
        if (this._visibility_ != null) {
            this._visibility_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._visibility_ = node;
    }

    public TKwAbstract getKwAbstract() {
        return this._kwAbstract_;
    }

    public void setKwAbstract(TKwAbstract node) {
        if (this._kwAbstract_ != null) {
            this._kwAbstract_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwAbstract_ = node;
    }

    public PType getType() {
        return this._type_;
    }

    public void setType(PType node) {
        if (this._type_ != null) {
            this._type_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PVariableDeclarator getVariableDeclarator() {
        return this._variableDeclarator_;
    }

    public void setVariableDeclarator(PVariableDeclarator node) {
        if (this._variableDeclarator_ != null) {
            this._variableDeclarator_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variableDeclarator_ = node;
    }

    public TSemi getSemi() {
        return this._semi_;
    }

    public void setSemi(TSemi node) {
        if (this._semi_ != null) {
            this._semi_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._annotations_)
                + toString(this._visibility_)
                + toString(this._kwAbstract_)
                + toString(this._type_)
                + toString(this._variableDeclarator_)
                + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._annotations_.remove(child)) {
            return;
        }

        if (this._visibility_ == child) {
            this._visibility_ = null;
            return;
        }

        if (this._kwAbstract_ == child) {
            this._kwAbstract_ = null;
            return;
        }

        if (this._type_ == child) {
            this._type_ = null;
            return;
        }

        if (this._variableDeclarator_ == child) {
            this._variableDeclarator_ = null;
            return;
        }

        if (this._semi_ == child) {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        for (ListIterator<PAnnotation> i = this._annotations_.listIterator(); i.hasNext(); ) {
            if (i.next() == oldChild) {
                if (newChild != null) {
                    i.set((PAnnotation) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if (this._visibility_ == oldChild) {
            setVisibility((PVisibility) newChild);
            return;
        }

        if (this._kwAbstract_ == oldChild) {
            setKwAbstract((TKwAbstract) newChild);
            return;
        }

        if (this._type_ == oldChild) {
            setType((PType) newChild);
            return;
        }

        if (this._variableDeclarator_ == oldChild) {
            setVariableDeclarator((PVariableDeclarator) newChild);
            return;
        }

        if (this._semi_ == oldChild) {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
