/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AAbstractActionClause extends PAbstractActionClause
{

    public AAbstractActionClause()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AAbstractActionClause();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAbstractActionClause(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
