/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AAmpAndExp extends PAndExp {
    private PAndExp _andExp_;
    private TAmp _amp_;
    private PEqualityExp _equalityExp_;

    public AAmpAndExp() {
        // Constructor
    }

    public AAmpAndExp(
            @SuppressWarnings("hiding") PAndExp _andExp_,
            @SuppressWarnings("hiding") TAmp _amp_,
            @SuppressWarnings("hiding") PEqualityExp _equalityExp_) {
        // Constructor
        setAndExp(_andExp_);

        setAmp(_amp_);

        setEqualityExp(_equalityExp_);

    }

    @Override
    public Object clone() {
        return new AAmpAndExp(
                cloneNode(this._andExp_),
                cloneNode(this._amp_),
                cloneNode(this._equalityExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAAmpAndExp(this);
    }

    public PAndExp getAndExp() {
        return this._andExp_;
    }

    public void setAndExp(PAndExp node) {
        if (this._andExp_ != null) {
            this._andExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExp_ = node;
    }

    public TAmp getAmp() {
        return this._amp_;
    }

    public void setAmp(TAmp node) {
        if (this._amp_ != null) {
            this._amp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._amp_ = node;
    }

    public PEqualityExp getEqualityExp() {
        return this._equalityExp_;
    }

    public void setEqualityExp(PEqualityExp node) {
        if (this._equalityExp_ != null) {
            this._equalityExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._andExp_)
                + toString(this._amp_)
                + toString(this._equalityExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._andExp_ == child) {
            this._andExp_ = null;
            return;
        }

        if (this._amp_ == child) {
            this._amp_ = null;
            return;
        }

        if (this._equalityExp_ == child) {
            this._equalityExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._andExp_ == oldChild) {
            setAndExp((PAndExp) newChild);
            return;
        }

        if (this._amp_ == oldChild) {
            setAmp((TAmp) newChild);
            return;
        }

        if (this._equalityExp_ == oldChild) {
            setEqualityExp((PEqualityExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
