/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AAssertDeclarationInnerConceptDecl extends PInnerConceptDecl {
    private PAssertDecl _assertDecl_;

    public AAssertDeclarationInnerConceptDecl() {
        // Constructor
    }

    public AAssertDeclarationInnerConceptDecl(
            @SuppressWarnings("hiding") PAssertDecl _assertDecl_) {
        // Constructor
        setAssertDecl(_assertDecl_);

    }

    @Override
    public Object clone() {
        return new AAssertDeclarationInnerConceptDecl(
                cloneNode(this._assertDecl_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAAssertDeclarationInnerConceptDecl(this);
    }

    public PAssertDecl getAssertDecl() {
        return this._assertDecl_;
    }

    public void setAssertDecl(PAssertDecl node) {
        if (this._assertDecl_ != null) {
            this._assertDecl_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assertDecl_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._assertDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._assertDecl_ == child) {
            this._assertDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._assertDecl_ == oldChild) {
            setAssertDecl((PAssertDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
