/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AAssignmentStatementExpression extends PStatementExpression
{
    private PAssignmentStatementExpression _assignmentStatementExpression_;

    public AAssignmentStatementExpression()
    {
        // Constructor
    }

    public AAssignmentStatementExpression(
        @SuppressWarnings("hiding") PAssignmentStatementExpression _assignmentStatementExpression_)
    {
        // Constructor
        setAssignmentStatementExpression(_assignmentStatementExpression_);

    }

    @Override
    public Object clone()
    {
        return new AAssignmentStatementExpression(
            cloneNode(this._assignmentStatementExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignmentStatementExpression(this);
    }

    public PAssignmentStatementExpression getAssignmentStatementExpression()
    {
        return this._assignmentStatementExpression_;
    }

    public void setAssignmentStatementExpression(PAssignmentStatementExpression node)
    {
        if(this._assignmentStatementExpression_ != null)
        {
            this._assignmentStatementExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignmentStatementExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignmentStatementExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignmentStatementExpression_ == child)
        {
            this._assignmentStatementExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignmentStatementExpression_ == oldChild)
        {
            setAssignmentStatementExpression((PAssignmentStatementExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
