/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ABarInclusiveOrExp extends PInclusiveOrExp
{
    private PInclusiveOrExp _inclusiveOrExp_;
    private TBar _bar_;
    private PExclusiveOrExp _exclusiveOrExp_;

    public ABarInclusiveOrExp()
    {
        // Constructor
    }

    public ABarInclusiveOrExp(
        @SuppressWarnings("hiding") PInclusiveOrExp _inclusiveOrExp_,
        @SuppressWarnings("hiding") TBar _bar_,
        @SuppressWarnings("hiding") PExclusiveOrExp _exclusiveOrExp_)
    {
        // Constructor
        setInclusiveOrExp(_inclusiveOrExp_);

        setBar(_bar_);

        setExclusiveOrExp(_exclusiveOrExp_);

    }

    @Override
    public Object clone()
    {
        return new ABarInclusiveOrExp(
            cloneNode(this._inclusiveOrExp_),
            cloneNode(this._bar_),
            cloneNode(this._exclusiveOrExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABarInclusiveOrExp(this);
    }

    public PInclusiveOrExp getInclusiveOrExp()
    {
        return this._inclusiveOrExp_;
    }

    public void setInclusiveOrExp(PInclusiveOrExp node)
    {
        if(this._inclusiveOrExp_ != null)
        {
            this._inclusiveOrExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inclusiveOrExp_ = node;
    }

    public TBar getBar()
    {
        return this._bar_;
    }

    public void setBar(TBar node)
    {
        if(this._bar_ != null)
        {
            this._bar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bar_ = node;
    }

    public PExclusiveOrExp getExclusiveOrExp()
    {
        return this._exclusiveOrExp_;
    }

    public void setExclusiveOrExp(PExclusiveOrExp node)
    {
        if(this._exclusiveOrExp_ != null)
        {
            this._exclusiveOrExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclusiveOrExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inclusiveOrExp_)
            + toString(this._bar_)
            + toString(this._exclusiveOrExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inclusiveOrExp_ == child)
        {
            this._inclusiveOrExp_ = null;
            return;
        }

        if(this._bar_ == child)
        {
            this._bar_ = null;
            return;
        }

        if(this._exclusiveOrExp_ == child)
        {
            this._exclusiveOrExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inclusiveOrExp_ == oldChild)
        {
            setInclusiveOrExp((PInclusiveOrExp) newChild);
            return;
        }

        if(this._bar_ == oldChild)
        {
            setBar((TBar) newChild);
            return;
        }

        if(this._exclusiveOrExp_ == oldChild)
        {
            setExclusiveOrExp((PExclusiveOrExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
