/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ABasicAnnotationAnnotation extends PAnnotation {
    private TAt _at_;
    private PAnnotationTag _tag_;

    public ABasicAnnotationAnnotation() {
        // Constructor
    }

    public ABasicAnnotationAnnotation(
            @SuppressWarnings("hiding") TAt _at_,
            @SuppressWarnings("hiding") PAnnotationTag _tag_) {
        // Constructor
        setAt(_at_);

        setTag(_tag_);

    }

    @Override
    public Object clone() {
        return new ABasicAnnotationAnnotation(
                cloneNode(this._at_),
                cloneNode(this._tag_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseABasicAnnotationAnnotation(this);
    }

    public TAt getAt() {
        return this._at_;
    }

    public void setAt(TAt node) {
        if (this._at_ != null) {
            this._at_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._at_ = node;
    }

    public PAnnotationTag getTag() {
        return this._tag_;
    }

    public void setTag(PAnnotationTag node) {
        if (this._tag_ != null) {
            this._tag_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tag_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._at_)
                + toString(this._tag_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._at_ == child) {
            this._at_ = null;
            return;
        }

        if (this._tag_ == child) {
            this._tag_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._at_ == oldChild) {
            setAt((TAt) newChild);
            return;
        }

        if (this._tag_ == oldChild) {
            setTag((PAnnotationTag) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
