/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ABeginMatchActionFmlActionExp extends PFmlActionExp
{
    private TKwBegin _kwBegin_;
    private TKwMatch _kwMatch_;
    private TUidentifier _conceptName_;
    private PFromClause _fromClause_;
    private PWhereClause _whereClause_;

    public ABeginMatchActionFmlActionExp()
    {
        // Constructor
    }

    public ABeginMatchActionFmlActionExp(
        @SuppressWarnings("hiding") TKwBegin _kwBegin_,
        @SuppressWarnings("hiding") TKwMatch _kwMatch_,
        @SuppressWarnings("hiding") TUidentifier _conceptName_,
        @SuppressWarnings("hiding") PFromClause _fromClause_,
        @SuppressWarnings("hiding") PWhereClause _whereClause_)
    {
        // Constructor
        setKwBegin(_kwBegin_);

        setKwMatch(_kwMatch_);

        setConceptName(_conceptName_);

        setFromClause(_fromClause_);

        setWhereClause(_whereClause_);

    }

    @Override
    public Object clone()
    {
        return new ABeginMatchActionFmlActionExp(
            cloneNode(this._kwBegin_),
            cloneNode(this._kwMatch_),
            cloneNode(this._conceptName_),
            cloneNode(this._fromClause_),
            cloneNode(this._whereClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABeginMatchActionFmlActionExp(this);
    }

    public TKwBegin getKwBegin()
    {
        return this._kwBegin_;
    }

    public void setKwBegin(TKwBegin node)
    {
        if(this._kwBegin_ != null)
        {
            this._kwBegin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwBegin_ = node;
    }

    public TKwMatch getKwMatch()
    {
        return this._kwMatch_;
    }

    public void setKwMatch(TKwMatch node)
    {
        if(this._kwMatch_ != null)
        {
            this._kwMatch_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwMatch_ = node;
    }

    public TUidentifier getConceptName()
    {
        return this._conceptName_;
    }

    public void setConceptName(TUidentifier node)
    {
        if(this._conceptName_ != null)
        {
            this._conceptName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conceptName_ = node;
    }

    public PFromClause getFromClause()
    {
        return this._fromClause_;
    }

    public void setFromClause(PFromClause node)
    {
        if(this._fromClause_ != null)
        {
            this._fromClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fromClause_ = node;
    }

    public PWhereClause getWhereClause()
    {
        return this._whereClause_;
    }

    public void setWhereClause(PWhereClause node)
    {
        if(this._whereClause_ != null)
        {
            this._whereClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whereClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwBegin_)
            + toString(this._kwMatch_)
            + toString(this._conceptName_)
            + toString(this._fromClause_)
            + toString(this._whereClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwBegin_ == child)
        {
            this._kwBegin_ = null;
            return;
        }

        if(this._kwMatch_ == child)
        {
            this._kwMatch_ = null;
            return;
        }

        if(this._conceptName_ == child)
        {
            this._conceptName_ = null;
            return;
        }

        if(this._fromClause_ == child)
        {
            this._fromClause_ = null;
            return;
        }

        if(this._whereClause_ == child)
        {
            this._whereClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwBegin_ == oldChild)
        {
            setKwBegin((TKwBegin) newChild);
            return;
        }

        if(this._kwMatch_ == oldChild)
        {
            setKwMatch((TKwMatch) newChild);
            return;
        }

        if(this._conceptName_ == oldChild)
        {
            setConceptName((TUidentifier) newChild);
            return;
        }

        if(this._fromClause_ == oldChild)
        {
            setFromClause((PFromClause) newChild);
            return;
        }

        if(this._whereClause_ == oldChild)
        {
            setWhereClause((PWhereClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
