/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ACaretExclusiveOrExp extends PExclusiveOrExp {
    private PExclusiveOrExp _exclusiveOrExp_;
    private TCaret _caret_;
    private PAndExp _andExp_;

    public ACaretExclusiveOrExp() {
        // Constructor
    }

    public ACaretExclusiveOrExp(
            @SuppressWarnings("hiding") PExclusiveOrExp _exclusiveOrExp_,
            @SuppressWarnings("hiding") TCaret _caret_,
            @SuppressWarnings("hiding") PAndExp _andExp_) {
        // Constructor
        setExclusiveOrExp(_exclusiveOrExp_);

        setCaret(_caret_);

        setAndExp(_andExp_);

    }

    @Override
    public Object clone() {
        return new ACaretExclusiveOrExp(
                cloneNode(this._exclusiveOrExp_),
                cloneNode(this._caret_),
                cloneNode(this._andExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseACaretExclusiveOrExp(this);
    }

    public PExclusiveOrExp getExclusiveOrExp() {
        return this._exclusiveOrExp_;
    }

    public void setExclusiveOrExp(PExclusiveOrExp node) {
        if (this._exclusiveOrExp_ != null) {
            this._exclusiveOrExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exclusiveOrExp_ = node;
    }

    public TCaret getCaret() {
        return this._caret_;
    }

    public void setCaret(TCaret node) {
        if (this._caret_ != null) {
            this._caret_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caret_ = node;
    }

    public PAndExp getAndExp() {
        return this._andExp_;
    }

    public void setAndExp(PAndExp node) {
        if (this._andExp_ != null) {
            this._andExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._andExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._exclusiveOrExp_)
                + toString(this._caret_)
                + toString(this._andExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._exclusiveOrExp_ == child) {
            this._exclusiveOrExp_ = null;
            return;
        }

        if (this._caret_ == child) {
            this._caret_ = null;
            return;
        }

        if (this._andExp_ == child) {
            this._andExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._exclusiveOrExp_ == oldChild) {
            setExclusiveOrExp((PExclusiveOrExp) newChild);
            return;
        }

        if (this._caret_ == oldChild) {
            setCaret((TCaret) newChild);
            return;
        }

        if (this._andExp_ == oldChild) {
            setAndExp((PAndExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
