/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

@SuppressWarnings("nls")
public final class ACastUnaryExpNotPlusMinus extends PUnaryExpNotPlusMinus {
    private final LinkedList<PDim> _dims_ = new LinkedList<PDim>();
    private TLPar _lPar_;
    private PType _type_;
    private TRPar _rPar_;
    private PUnaryExp _unaryExp_;

    public ACastUnaryExpNotPlusMinus() {
        // Constructor
    }

    public ACastUnaryExpNotPlusMinus(
            @SuppressWarnings("hiding") TLPar _lPar_,
            @SuppressWarnings("hiding") PType _type_,
            @SuppressWarnings("hiding") List<?> _dims_,
            @SuppressWarnings("hiding") TRPar _rPar_,
            @SuppressWarnings("hiding") PUnaryExp _unaryExp_) {
        // Constructor
        setLPar(_lPar_);

        setType(_type_);

        setDims(_dims_);

        setRPar(_rPar_);

        setUnaryExp(_unaryExp_);

    }

    @Override
    public Object clone() {
        return new ACastUnaryExpNotPlusMinus(
                cloneNode(this._lPar_),
                cloneNode(this._type_),
                cloneList(this._dims_),
                cloneNode(this._rPar_),
                cloneNode(this._unaryExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseACastUnaryExpNotPlusMinus(this);
    }

    public TLPar getLPar() {
        return this._lPar_;
    }

    public void setLPar(TLPar node) {
        if (this._lPar_ != null) {
            this._lPar_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PType getType() {
        return this._type_;
    }

    public void setType(PType node) {
        if (this._type_ != null) {
            this._type_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public LinkedList<PDim> getDims() {
        return this._dims_;
    }

    public void setDims(List<?> list) {
        for (PDim e : this._dims_) {
            e.parent(null);
        }
        this._dims_.clear();

        for (Object obj_e : list) {
            PDim e = (PDim) obj_e;
            if (e.parent() != null) {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._dims_.add(e);
        }
    }

    public TRPar getRPar() {
        return this._rPar_;
    }

    public void setRPar(TRPar node) {
        if (this._rPar_ != null) {
            this._rPar_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    public PUnaryExp getUnaryExp() {
        return this._unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node) {
        if (this._unaryExp_ != null) {
            this._unaryExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._lPar_)
                + toString(this._type_)
                + toString(this._dims_)
                + toString(this._rPar_)
                + toString(this._unaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._lPar_ == child) {
            this._lPar_ = null;
            return;
        }

        if (this._type_ == child) {
            this._type_ = null;
            return;
        }

        if (this._dims_.remove(child)) {
            return;
        }

        if (this._rPar_ == child) {
            this._rPar_ = null;
            return;
        }

        if (this._unaryExp_ == child) {
            this._unaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._lPar_ == oldChild) {
            setLPar((TLPar) newChild);
            return;
        }

        if (this._type_ == oldChild) {
            setType((PType) newChild);
            return;
        }

        for (ListIterator<PDim> i = this._dims_.listIterator(); i.hasNext(); ) {
            if (i.next() == oldChild) {
                if (newChild != null) {
                    i.set((PDim) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if (this._rPar_ == oldChild) {
            setRPar((TRPar) newChild);
            return;
        }

        if (this._unaryExp_ == oldChild) {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
