/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ACharacterLiteral extends PLiteral {
    private TLitCharacter _litCharacter_;

    public ACharacterLiteral() {
        // Constructor
    }

    public ACharacterLiteral(
            @SuppressWarnings("hiding") TLitCharacter _litCharacter_) {
        // Constructor
        setLitCharacter(_litCharacter_);

    }

    @Override
    public Object clone() {
        return new ACharacterLiteral(
                cloneNode(this._litCharacter_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseACharacterLiteral(this);
    }

    public TLitCharacter getLitCharacter() {
        return this._litCharacter_;
    }

    public void setLitCharacter(TLitCharacter node) {
        if (this._litCharacter_ != null) {
            this._litCharacter_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litCharacter_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._litCharacter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._litCharacter_ == child) {
            this._litCharacter_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._litCharacter_ == oldChild) {
            setLitCharacter((TLitCharacter) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
