/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ACompilationUnitEntryPoint extends PEntryPoint {
    private TStartCompilationUnit _startCompilationUnit_;
    private PFmlCompilationUnit _cu_;

    public ACompilationUnitEntryPoint() {
        // Constructor
    }

    public ACompilationUnitEntryPoint(
            @SuppressWarnings("hiding") TStartCompilationUnit _startCompilationUnit_,
            @SuppressWarnings("hiding") PFmlCompilationUnit _cu_) {
        // Constructor
        setStartCompilationUnit(_startCompilationUnit_);

        setCu(_cu_);

    }

    @Override
    public Object clone() {
        return new ACompilationUnitEntryPoint(
                cloneNode(this._startCompilationUnit_),
                cloneNode(this._cu_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseACompilationUnitEntryPoint(this);
    }

    public TStartCompilationUnit getStartCompilationUnit() {
        return this._startCompilationUnit_;
    }

    public void setStartCompilationUnit(TStartCompilationUnit node) {
        if (this._startCompilationUnit_ != null) {
            this._startCompilationUnit_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startCompilationUnit_ = node;
    }

    public PFmlCompilationUnit getCu() {
        return this._cu_;
    }

    public void setCu(PFmlCompilationUnit node) {
        if (this._cu_ != null) {
            this._cu_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cu_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._startCompilationUnit_)
                + toString(this._cu_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._startCompilationUnit_ == child) {
            this._startCompilationUnit_ = null;
            return;
        }

        if (this._cu_ == child) {
            this._cu_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._startCompilationUnit_ == oldChild) {
            setStartCompilationUnit((TStartCompilationUnit) newChild);
            return;
        }

        if (this._cu_ == oldChild) {
            setCu((PFmlCompilationUnit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
