/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AComplexType extends PType
{
    private PReferenceType _referenceType_;
    private PAtVersion _atVersion_;

    public AComplexType()
    {
        // Constructor
    }

    public AComplexType(
        @SuppressWarnings("hiding") PReferenceType _referenceType_,
        @SuppressWarnings("hiding") PAtVersion _atVersion_)
    {
        // Constructor
        setReferenceType(_referenceType_);

        setAtVersion(_atVersion_);

    }

    @Override
    public Object clone()
    {
        return new AComplexType(
            cloneNode(this._referenceType_),
            cloneNode(this._atVersion_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComplexType(this);
    }

    public PReferenceType getReferenceType()
    {
        return this._referenceType_;
    }

    public void setReferenceType(PReferenceType node)
    {
        if(this._referenceType_ != null)
        {
            this._referenceType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._referenceType_ = node;
    }

    public PAtVersion getAtVersion()
    {
        return this._atVersion_;
    }

    public void setAtVersion(PAtVersion node)
    {
        if(this._atVersion_ != null)
        {
            this._atVersion_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atVersion_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._referenceType_)
            + toString(this._atVersion_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._referenceType_ == child)
        {
            this._referenceType_ = null;
            return;
        }

        if(this._atVersion_ == child)
        {
            this._atVersion_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._referenceType_ == oldChild)
        {
            setReferenceType((PReferenceType) newChild);
            return;
        }

        if(this._atVersion_ == oldChild)
        {
            setAtVersion((PAtVersion) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
