/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ACompositeTidentAnnotationTag extends PAnnotationTag {
    private PCompositeTident _compositeTident_;

    public ACompositeTidentAnnotationTag() {
        // Constructor
    }

    public ACompositeTidentAnnotationTag(
            @SuppressWarnings("hiding") PCompositeTident _compositeTident_) {
        // Constructor
        setCompositeTident(_compositeTident_);

    }

    @Override
    public Object clone() {
        return new ACompositeTidentAnnotationTag(
                cloneNode(this._compositeTident_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseACompositeTidentAnnotationTag(this);
    }

    public PCompositeTident getCompositeTident() {
        return this._compositeTident_;
    }

    public void setCompositeTident(PCompositeTident node) {
        if (this._compositeTident_ != null) {
            this._compositeTident_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compositeTident_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._compositeTident_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._compositeTident_ == child) {
            this._compositeTident_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._compositeTident_ == oldChild) {
            setCompositeTident((PCompositeTident) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
