/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

@SuppressWarnings("nls")
public final class ACompositeCident extends PCompositeCident {
    private final LinkedList<PIdentifierPrefix> _prefixes_ = new LinkedList<PIdentifierPrefix>();
    private TCidentifier _identifier_;

    public ACompositeCident() {
        // Constructor
    }

    public ACompositeCident(
            @SuppressWarnings("hiding") List<?> _prefixes_,
            @SuppressWarnings("hiding") TCidentifier _identifier_) {
        // Constructor
        setPrefixes(_prefixes_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone() {
        return new ACompositeCident(
                cloneList(this._prefixes_),
                cloneNode(this._identifier_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseACompositeCident(this);
    }

    public LinkedList<PIdentifierPrefix> getPrefixes() {
        return this._prefixes_;
    }

    public void setPrefixes(List<?> list) {
        for (PIdentifierPrefix e : this._prefixes_) {
            e.parent(null);
        }
        this._prefixes_.clear();

        for (Object obj_e : list) {
            PIdentifierPrefix e = (PIdentifierPrefix) obj_e;
            if (e.parent() != null) {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._prefixes_.add(e);
        }
    }

    public TCidentifier getIdentifier() {
        return this._identifier_;
    }

    public void setIdentifier(TCidentifier node) {
        if (this._identifier_ != null) {
            this._identifier_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._prefixes_)
                + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._prefixes_.remove(child)) {
            return;
        }

        if (this._identifier_ == child) {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        for (ListIterator<PIdentifierPrefix> i = this._prefixes_.listIterator(); i.hasNext(); ) {
            if (i.next() == oldChild) {
                if (newChild != null) {
                    i.set((PIdentifierPrefix) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if (this._identifier_ == oldChild) {
            setIdentifier((TCidentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
