/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ACompositeTident extends PCompositeTident
{
    private final LinkedList<PIdentifierPrefix> _prefixes_ = new LinkedList<PIdentifierPrefix>();
    private TUidentifier _identifier_;
    private final LinkedList<PCompositeTidentSuffix> _suffixes_ = new LinkedList<PCompositeTidentSuffix>();

    public ACompositeTident()
    {
        // Constructor
    }

    public ACompositeTident(
        @SuppressWarnings("hiding") List<?> _prefixes_,
        @SuppressWarnings("hiding") TUidentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _suffixes_)
    {
        // Constructor
        setPrefixes(_prefixes_);

        setIdentifier(_identifier_);

        setSuffixes(_suffixes_);

    }

    @Override
    public Object clone()
    {
        return new ACompositeTident(
            cloneList(this._prefixes_),
            cloneNode(this._identifier_),
            cloneList(this._suffixes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompositeTident(this);
    }

    public LinkedList<PIdentifierPrefix> getPrefixes()
    {
        return this._prefixes_;
    }

    public void setPrefixes(List<?> list)
    {
        for(PIdentifierPrefix e : this._prefixes_)
        {
            e.parent(null);
        }
        this._prefixes_.clear();

        for(Object obj_e : list)
        {
            PIdentifierPrefix e = (PIdentifierPrefix) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._prefixes_.add(e);
        }
    }

    public TUidentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TUidentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PCompositeTidentSuffix> getSuffixes()
    {
        return this._suffixes_;
    }

    public void setSuffixes(List<?> list)
    {
        for(PCompositeTidentSuffix e : this._suffixes_)
        {
            e.parent(null);
        }
        this._suffixes_.clear();

        for(Object obj_e : list)
        {
            PCompositeTidentSuffix e = (PCompositeTidentSuffix) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._suffixes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prefixes_)
            + toString(this._identifier_)
            + toString(this._suffixes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prefixes_.remove(child))
        {
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._suffixes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PIdentifierPrefix> i = this._prefixes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIdentifierPrefix) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TUidentifier) newChild);
            return;
        }

        for(ListIterator<PCompositeTidentSuffix> i = this._suffixes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCompositeTidentSuffix) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
