/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AComplexFormalArgument extends PFormalArgument
{
    private TKwRequired _kwRequired_;
    private PReferenceType _referenceType_;
    private TLidentifier _argName_;
    private PDefaultArgumentValue _defaultArgumentValue_;

    public AComplexFormalArgument()
    {
        // Constructor
    }

    public AComplexFormalArgument(
        @SuppressWarnings("hiding") TKwRequired _kwRequired_,
        @SuppressWarnings("hiding") PReferenceType _referenceType_,
        @SuppressWarnings("hiding") TLidentifier _argName_,
        @SuppressWarnings("hiding") PDefaultArgumentValue _defaultArgumentValue_)
    {
        // Constructor
        setKwRequired(_kwRequired_);

        setReferenceType(_referenceType_);

        setArgName(_argName_);

        setDefaultArgumentValue(_defaultArgumentValue_);

    }

    @Override
    public Object clone()
    {
        return new AComplexFormalArgument(
            cloneNode(this._kwRequired_),
            cloneNode(this._referenceType_),
            cloneNode(this._argName_),
            cloneNode(this._defaultArgumentValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComplexFormalArgument(this);
    }

    public TKwRequired getKwRequired()
    {
        return this._kwRequired_;
    }

    public void setKwRequired(TKwRequired node)
    {
        if(this._kwRequired_ != null)
        {
            this._kwRequired_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwRequired_ = node;
    }

    public PReferenceType getReferenceType()
    {
        return this._referenceType_;
    }

    public void setReferenceType(PReferenceType node)
    {
        if(this._referenceType_ != null)
        {
            this._referenceType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._referenceType_ = node;
    }

    public TLidentifier getArgName()
    {
        return this._argName_;
    }

    public void setArgName(TLidentifier node)
    {
        if(this._argName_ != null)
        {
            this._argName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argName_ = node;
    }

    public PDefaultArgumentValue getDefaultArgumentValue()
    {
        return this._defaultArgumentValue_;
    }

    public void setDefaultArgumentValue(PDefaultArgumentValue node)
    {
        if(this._defaultArgumentValue_ != null)
        {
            this._defaultArgumentValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._defaultArgumentValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwRequired_)
            + toString(this._referenceType_)
            + toString(this._argName_)
            + toString(this._defaultArgumentValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwRequired_ == child)
        {
            this._kwRequired_ = null;
            return;
        }

        if(this._referenceType_ == child)
        {
            this._referenceType_ = null;
            return;
        }

        if(this._argName_ == child)
        {
            this._argName_ = null;
            return;
        }

        if(this._defaultArgumentValue_ == child)
        {
            this._defaultArgumentValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwRequired_ == oldChild)
        {
            setKwRequired((TKwRequired) newChild);
            return;
        }

        if(this._referenceType_ == oldChild)
        {
            setReferenceType((PReferenceType) newChild);
            return;
        }

        if(this._argName_ == oldChild)
        {
            setArgName((TLidentifier) newChild);
            return;
        }

        if(this._defaultArgumentValue_ == oldChild)
        {
            setDefaultArgumentValue((PDefaultArgumentValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
