/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ACommandEntryPoint extends PEntryPoint {
    private TStartCommand _startCommand_;
    private PCommand _command_;

    public ACommandEntryPoint() {
        // Constructor
    }

    public ACommandEntryPoint(
            @SuppressWarnings("hiding") TStartCommand _startCommand_,
            @SuppressWarnings("hiding") PCommand _command_) {
        // Constructor
        setStartCommand(_startCommand_);

        setCommand(_command_);

    }

    @Override
    public Object clone() {
        return new ACommandEntryPoint(
                cloneNode(this._startCommand_),
                cloneNode(this._command_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseACommandEntryPoint(this);
    }

    public TStartCommand getStartCommand() {
        return this._startCommand_;
    }

    public void setStartCommand(TStartCommand node) {
        if (this._startCommand_ != null) {
            this._startCommand_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._startCommand_ = node;
    }

    public PCommand getCommand() {
        return this._command_;
    }

    public void setCommand(PCommand node) {
        if (this._command_ != null) {
            this._command_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._command_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._startCommand_)
                + toString(this._command_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._startCommand_ == child) {
            this._startCommand_ = null;
            return;
        }

        if (this._command_ == child) {
            this._command_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._startCommand_ == oldChild) {
            setStartCommand((TStartCommand) newChild);
            return;
        }

        if (this._command_ == oldChild) {
            setCommand((PCommand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
