/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AConceptDeclarationInnerConceptDecl extends PInnerConceptDecl {
    private PConceptDecl _conceptDecl_;

    public AConceptDeclarationInnerConceptDecl() {
        // Constructor
    }

    public AConceptDeclarationInnerConceptDecl(
            @SuppressWarnings("hiding") PConceptDecl _conceptDecl_) {
        // Constructor
        setConceptDecl(_conceptDecl_);

    }

    @Override
    public Object clone() {
        return new AConceptDeclarationInnerConceptDecl(
                cloneNode(this._conceptDecl_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAConceptDeclarationInnerConceptDecl(this);
    }

    public PConceptDecl getConceptDecl() {
        return this._conceptDecl_;
    }

    public void setConceptDecl(PConceptDecl node) {
        if (this._conceptDecl_ != null) {
            this._conceptDecl_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conceptDecl_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._conceptDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._conceptDecl_ == child) {
            this._conceptDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._conceptDecl_ == oldChild) {
            setConceptDecl((PConceptDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
