/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AConcatenedSimplePath extends PSimplePath {
    private PSimplePathTerminal _simplePathTerminal_;
    private PSimplePath _simplePath_;

    public AConcatenedSimplePath() {
        // Constructor
    }

    public AConcatenedSimplePath(
            @SuppressWarnings("hiding") PSimplePathTerminal _simplePathTerminal_,
            @SuppressWarnings("hiding") PSimplePath _simplePath_) {
        // Constructor
        setSimplePathTerminal(_simplePathTerminal_);

        setSimplePath(_simplePath_);

    }

    @Override
    public Object clone() {
        return new AConcatenedSimplePath(
                cloneNode(this._simplePathTerminal_),
                cloneNode(this._simplePath_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAConcatenedSimplePath(this);
    }

    public PSimplePathTerminal getSimplePathTerminal() {
        return this._simplePathTerminal_;
    }

    public void setSimplePathTerminal(PSimplePathTerminal node) {
        if (this._simplePathTerminal_ != null) {
            this._simplePathTerminal_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simplePathTerminal_ = node;
    }

    public PSimplePath getSimplePath() {
        return this._simplePath_;
    }

    public void setSimplePath(PSimplePath node) {
        if (this._simplePath_ != null) {
            this._simplePath_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simplePath_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._simplePathTerminal_)
                + toString(this._simplePath_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._simplePathTerminal_ == child) {
            this._simplePathTerminal_ = null;
            return;
        }

        if (this._simplePath_ == child) {
            this._simplePath_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._simplePathTerminal_ == oldChild) {
            setSimplePathTerminal((PSimplePathTerminal) newChild);
            return;
        }

        if (this._simplePath_ == oldChild) {
            setSimplePath((PSimplePath) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
