/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AConnectActionFmlActionExp extends PFmlActionExp
{
    private TKwConnect _kwConnect_;
    private PLeftHandSide _connect_;
    private TKwUsing _kwUsing_;
    private PExpression _using_;

    public AConnectActionFmlActionExp()
    {
        // Constructor
    }

    public AConnectActionFmlActionExp(
        @SuppressWarnings("hiding") TKwConnect _kwConnect_,
        @SuppressWarnings("hiding") PLeftHandSide _connect_,
        @SuppressWarnings("hiding") TKwUsing _kwUsing_,
        @SuppressWarnings("hiding") PExpression _using_)
    {
        // Constructor
        setKwConnect(_kwConnect_);

        setConnect(_connect_);

        setKwUsing(_kwUsing_);

        setUsing(_using_);

    }

    @Override
    public Object clone()
    {
        return new AConnectActionFmlActionExp(
            cloneNode(this._kwConnect_),
            cloneNode(this._connect_),
            cloneNode(this._kwUsing_),
            cloneNode(this._using_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConnectActionFmlActionExp(this);
    }

    public TKwConnect getKwConnect()
    {
        return this._kwConnect_;
    }

    public void setKwConnect(TKwConnect node)
    {
        if(this._kwConnect_ != null)
        {
            this._kwConnect_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwConnect_ = node;
    }

    public PLeftHandSide getConnect()
    {
        return this._connect_;
    }

    public void setConnect(PLeftHandSide node)
    {
        if(this._connect_ != null)
        {
            this._connect_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._connect_ = node;
    }

    public TKwUsing getKwUsing()
    {
        return this._kwUsing_;
    }

    public void setKwUsing(TKwUsing node)
    {
        if(this._kwUsing_ != null)
        {
            this._kwUsing_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwUsing_ = node;
    }

    public PExpression getUsing()
    {
        return this._using_;
    }

    public void setUsing(PExpression node)
    {
        if(this._using_ != null)
        {
            this._using_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._using_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwConnect_)
            + toString(this._connect_)
            + toString(this._kwUsing_)
            + toString(this._using_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwConnect_ == child)
        {
            this._kwConnect_ = null;
            return;
        }

        if(this._connect_ == child)
        {
            this._connect_ = null;
            return;
        }

        if(this._kwUsing_ == child)
        {
            this._kwUsing_ = null;
            return;
        }

        if(this._using_ == child)
        {
            this._using_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwConnect_ == oldChild)
        {
            setKwConnect((TKwConnect) newChild);
            return;
        }

        if(this._connect_ == oldChild)
        {
            setConnect((PLeftHandSide) newChild);
            return;
        }

        if(this._kwUsing_ == oldChild)
        {
            setKwUsing((TKwUsing) newChild);
            return;
        }

        if(this._using_ == oldChild)
        {
            setUsing((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
