/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADeleteAbstractActionClause extends PAbstractActionClause {
    private PDeleteClause _deleteClause_;

    public ADeleteAbstractActionClause() {
        // Constructor
    }

    public ADeleteAbstractActionClause(
            @SuppressWarnings("hiding") PDeleteClause _deleteClause_) {
        // Constructor
        setDeleteClause(_deleteClause_);

    }

    @Override
    public Object clone() {
        return new ADeleteAbstractActionClause(
                cloneNode(this._deleteClause_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseADeleteAbstractActionClause(this);
    }

    public PDeleteClause getDeleteClause() {
        return this._deleteClause_;
    }

    public void setDeleteClause(PDeleteClause node) {
        if (this._deleteClause_ != null) {
            this._deleteClause_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._deleteClause_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._deleteClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._deleteClause_ == child) {
            this._deleteClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._deleteClause_ == oldChild) {
            setDeleteClause((PDeleteClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
