/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ADoubleDotPath extends PPath
{
    private TDotDot _dotDot_;

    public ADoubleDotPath()
    {
        // Constructor
    }

    public ADoubleDotPath(
        @SuppressWarnings("hiding") TDotDot _dotDot_)
    {
        // Constructor
        setDotDot(_dotDot_);

    }

    @Override
    public Object clone()
    {
        return new ADoubleDotPath(
            cloneNode(this._dotDot_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADoubleDotPath(this);
    }

    public TDotDot getDotDot()
    {
        return this._dotDot_;
    }

    public void setDotDot(TDotDot node)
    {
        if(this._dotDot_ != null)
        {
            this._dotDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dotDot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dotDot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dotDot_ == child)
        {
            this._dotDot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dotDot_ == oldChild)
        {
            setDotDot((TDotDot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
