/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AEmarkUnaryExpNotPlusMinus extends PUnaryExpNotPlusMinus {
    private TEmark _emark_;
    private PUnaryExp _unaryExp_;

    public AEmarkUnaryExpNotPlusMinus() {
        // Constructor
    }

    public AEmarkUnaryExpNotPlusMinus(
            @SuppressWarnings("hiding") TEmark _emark_,
            @SuppressWarnings("hiding") PUnaryExp _unaryExp_) {
        // Constructor
        setEmark(_emark_);

        setUnaryExp(_unaryExp_);

    }

    @Override
    public Object clone() {
        return new AEmarkUnaryExpNotPlusMinus(
                cloneNode(this._emark_),
                cloneNode(this._unaryExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAEmarkUnaryExpNotPlusMinus(this);
    }

    public TEmark getEmark() {
        return this._emark_;
    }

    public void setEmark(TEmark node) {
        if (this._emark_ != null) {
            this._emark_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._emark_ = node;
    }

    public PUnaryExp getUnaryExp() {
        return this._unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node) {
        if (this._unaryExp_ != null) {
            this._unaryExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._emark_)
                + toString(this._unaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._emark_ == child) {
            this._emark_ = null;
            return;
        }

        if (this._unaryExp_ == child) {
            this._unaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._emark_ == oldChild) {
            setEmark((TEmark) newChild);
            return;
        }

        if (this._unaryExp_ == oldChild) {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
