/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AEnumValue extends PEnumValue
{
    private TCidentifier _cidentifier_;

    public AEnumValue()
    {
        // Constructor
    }

    public AEnumValue(
        @SuppressWarnings("hiding") TCidentifier _cidentifier_)
    {
        // Constructor
        setCidentifier(_cidentifier_);

    }

    @Override
    public Object clone()
    {
        return new AEnumValue(
            cloneNode(this._cidentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnumValue(this);
    }

    public TCidentifier getCidentifier()
    {
        return this._cidentifier_;
    }

    public void setCidentifier(TCidentifier node)
    {
        if(this._cidentifier_ != null)
        {
            this._cidentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cidentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cidentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cidentifier_ == child)
        {
            this._cidentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cidentifier_ == oldChild)
        {
            setCidentifier((TCidentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
