/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AEnumDeclarationInnerConceptDecl extends PInnerConceptDecl
{
    private PEnumDecl _enumDecl_;

    public AEnumDeclarationInnerConceptDecl()
    {
        // Constructor
    }

    public AEnumDeclarationInnerConceptDecl(
        @SuppressWarnings("hiding") PEnumDecl _enumDecl_)
    {
        // Constructor
        setEnumDecl(_enumDecl_);

    }

    @Override
    public Object clone()
    {
        return new AEnumDeclarationInnerConceptDecl(
            cloneNode(this._enumDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnumDeclarationInnerConceptDecl(this);
    }

    public PEnumDecl getEnumDecl()
    {
        return this._enumDecl_;
    }

    public void setEnumDecl(PEnumDecl node)
    {
        if(this._enumDecl_ != null)
        {
            this._enumDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enumDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enumDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enumDecl_ == child)
        {
            this._enumDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enumDecl_ == oldChild)
        {
            setEnumDecl((PEnumDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
