/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AEnumDecl extends PEnumDecl
{
    private final LinkedList<PAnnotation> _annotations_ = new LinkedList<PAnnotation>();
    private PVisibility _visibility_;
    private TKwEnum _kwEnum_;
    private TUidentifier _uidentifier_;
    private TLBrc _lBrc_;
    private PEnumValuesList _enumValuesList_;
    private TRBrc _rBrc_;

    public AEnumDecl()
    {
        // Constructor
    }

    public AEnumDecl(
        @SuppressWarnings("hiding") List<?> _annotations_,
        @SuppressWarnings("hiding") PVisibility _visibility_,
        @SuppressWarnings("hiding") TKwEnum _kwEnum_,
        @SuppressWarnings("hiding") TUidentifier _uidentifier_,
        @SuppressWarnings("hiding") TLBrc _lBrc_,
        @SuppressWarnings("hiding") PEnumValuesList _enumValuesList_,
        @SuppressWarnings("hiding") TRBrc _rBrc_)
    {
        // Constructor
        setAnnotations(_annotations_);

        setVisibility(_visibility_);

        setKwEnum(_kwEnum_);

        setUidentifier(_uidentifier_);

        setLBrc(_lBrc_);

        setEnumValuesList(_enumValuesList_);

        setRBrc(_rBrc_);

    }

    @Override
    public Object clone()
    {
        return new AEnumDecl(
            cloneList(this._annotations_),
            cloneNode(this._visibility_),
            cloneNode(this._kwEnum_),
            cloneNode(this._uidentifier_),
            cloneNode(this._lBrc_),
            cloneNode(this._enumValuesList_),
            cloneNode(this._rBrc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEnumDecl(this);
    }

    public LinkedList<PAnnotation> getAnnotations()
    {
        return this._annotations_;
    }

    public void setAnnotations(List<?> list)
    {
        for(PAnnotation e : this._annotations_)
        {
            e.parent(null);
        }
        this._annotations_.clear();

        for(Object obj_e : list)
        {
            PAnnotation e = (PAnnotation) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._annotations_.add(e);
        }
    }

    public PVisibility getVisibility()
    {
        return this._visibility_;
    }

    public void setVisibility(PVisibility node)
    {
        if(this._visibility_ != null)
        {
            this._visibility_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._visibility_ = node;
    }

    public TKwEnum getKwEnum()
    {
        return this._kwEnum_;
    }

    public void setKwEnum(TKwEnum node)
    {
        if(this._kwEnum_ != null)
        {
            this._kwEnum_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwEnum_ = node;
    }

    public TUidentifier getUidentifier()
    {
        return this._uidentifier_;
    }

    public void setUidentifier(TUidentifier node)
    {
        if(this._uidentifier_ != null)
        {
            this._uidentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._uidentifier_ = node;
    }

    public TLBrc getLBrc()
    {
        return this._lBrc_;
    }

    public void setLBrc(TLBrc node)
    {
        if(this._lBrc_ != null)
        {
            this._lBrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrc_ = node;
    }

    public PEnumValuesList getEnumValuesList()
    {
        return this._enumValuesList_;
    }

    public void setEnumValuesList(PEnumValuesList node)
    {
        if(this._enumValuesList_ != null)
        {
            this._enumValuesList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enumValuesList_ = node;
    }

    public TRBrc getRBrc()
    {
        return this._rBrc_;
    }

    public void setRBrc(TRBrc node)
    {
        if(this._rBrc_ != null)
        {
            this._rBrc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._annotations_)
            + toString(this._visibility_)
            + toString(this._kwEnum_)
            + toString(this._uidentifier_)
            + toString(this._lBrc_)
            + toString(this._enumValuesList_)
            + toString(this._rBrc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._annotations_.remove(child))
        {
            return;
        }

        if(this._visibility_ == child)
        {
            this._visibility_ = null;
            return;
        }

        if(this._kwEnum_ == child)
        {
            this._kwEnum_ = null;
            return;
        }

        if(this._uidentifier_ == child)
        {
            this._uidentifier_ = null;
            return;
        }

        if(this._lBrc_ == child)
        {
            this._lBrc_ = null;
            return;
        }

        if(this._enumValuesList_ == child)
        {
            this._enumValuesList_ = null;
            return;
        }

        if(this._rBrc_ == child)
        {
            this._rBrc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAnnotation> i = this._annotations_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAnnotation) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._visibility_ == oldChild)
        {
            setVisibility((PVisibility) newChild);
            return;
        }

        if(this._kwEnum_ == oldChild)
        {
            setKwEnum((TKwEnum) newChild);
            return;
        }

        if(this._uidentifier_ == oldChild)
        {
            setUidentifier((TUidentifier) newChild);
            return;
        }

        if(this._lBrc_ == oldChild)
        {
            setLBrc((TLBrc) newChild);
            return;
        }

        if(this._enumValuesList_ == oldChild)
        {
            setEnumValuesList((PEnumValuesList) newChild);
            return;
        }

        if(this._rBrc_ == oldChild)
        {
            setRBrc((TRBrc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
