/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AEqEqualityExp extends PEqualityExp
{
    private PEqualityExp _equalityExp_;
    private TEq _eq_;
    private PRelationalExp _relationalExp_;

    public AEqEqualityExp()
    {
        // Constructor
    }

    public AEqEqualityExp(
        @SuppressWarnings("hiding") PEqualityExp _equalityExp_,
        @SuppressWarnings("hiding") TEq _eq_,
        @SuppressWarnings("hiding") PRelationalExp _relationalExp_)
    {
        // Constructor
        setEqualityExp(_equalityExp_);

        setEq(_eq_);

        setRelationalExp(_relationalExp_);

    }

    @Override
    public Object clone()
    {
        return new AEqEqualityExp(
            cloneNode(this._equalityExp_),
            cloneNode(this._eq_),
            cloneNode(this._relationalExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqEqualityExp(this);
    }

    public PEqualityExp getEqualityExp()
    {
        return this._equalityExp_;
    }

    public void setEqualityExp(PEqualityExp node)
    {
        if(this._equalityExp_ != null)
        {
            this._equalityExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExp_ = node;
    }

    public TEq getEq()
    {
        return this._eq_;
    }

    public void setEq(TEq node)
    {
        if(this._eq_ != null)
        {
            this._eq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eq_ = node;
    }

    public PRelationalExp getRelationalExp()
    {
        return this._relationalExp_;
    }

    public void setRelationalExp(PRelationalExp node)
    {
        if(this._relationalExp_ != null)
        {
            this._relationalExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityExp_)
            + toString(this._eq_)
            + toString(this._relationalExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityExp_ == child)
        {
            this._equalityExp_ = null;
            return;
        }

        if(this._eq_ == child)
        {
            this._eq_ = null;
            return;
        }

        if(this._relationalExp_ == child)
        {
            this._relationalExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityExp_ == oldChild)
        {
            setEqualityExp((PEqualityExp) newChild);
            return;
        }

        if(this._eq_ == oldChild)
        {
            setEq((TEq) newChild);
            return;
        }

        if(this._relationalExp_ == oldChild)
        {
            setRelationalExp((PRelationalExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
