/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

@SuppressWarnings("nls")
public final class AEventDecl extends PEventDecl {
    private final LinkedList<PAnnotation> _annotations_ = new LinkedList<PAnnotation>();
    private final LinkedList<PInnerConceptDecl> _innerConceptDeclaration_ = new LinkedList<PInnerConceptDecl>();
    private PVisibility _visibility_;
    private TKwAbstract _kwAbstract_;
    private TKwEvent _kwEvent_;
    private TUidentifier _uidentifier_;
    private PSuperClause _superClause_;
    private PInsideClause _insideClause_;
    private TLBrc _lBrc_;
    private TRBrc _rBrc_;

    public AEventDecl() {
        // Constructor
    }

    public AEventDecl(
            @SuppressWarnings("hiding") List<?> _annotations_,
            @SuppressWarnings("hiding") PVisibility _visibility_,
            @SuppressWarnings("hiding") TKwAbstract _kwAbstract_,
            @SuppressWarnings("hiding") TKwEvent _kwEvent_,
            @SuppressWarnings("hiding") TUidentifier _uidentifier_,
            @SuppressWarnings("hiding") PSuperClause _superClause_,
            @SuppressWarnings("hiding") PInsideClause _insideClause_,
            @SuppressWarnings("hiding") TLBrc _lBrc_,
            @SuppressWarnings("hiding") List<?> _innerConceptDeclaration_,
            @SuppressWarnings("hiding") TRBrc _rBrc_) {
        // Constructor
        setAnnotations(_annotations_);

        setVisibility(_visibility_);

        setKwAbstract(_kwAbstract_);

        setKwEvent(_kwEvent_);

        setUidentifier(_uidentifier_);

        setSuperClause(_superClause_);

        setInsideClause(_insideClause_);

        setLBrc(_lBrc_);

        setInnerConceptDeclaration(_innerConceptDeclaration_);

        setRBrc(_rBrc_);

    }

    @Override
    public Object clone() {
        return new AEventDecl(
                cloneList(this._annotations_),
                cloneNode(this._visibility_),
                cloneNode(this._kwAbstract_),
                cloneNode(this._kwEvent_),
                cloneNode(this._uidentifier_),
                cloneNode(this._superClause_),
                cloneNode(this._insideClause_),
                cloneNode(this._lBrc_),
                cloneList(this._innerConceptDeclaration_),
                cloneNode(this._rBrc_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAEventDecl(this);
    }

    public LinkedList<PAnnotation> getAnnotations() {
        return this._annotations_;
    }

    public void setAnnotations(List<?> list) {
        for (PAnnotation e : this._annotations_) {
            e.parent(null);
        }
        this._annotations_.clear();

        for (Object obj_e : list) {
            PAnnotation e = (PAnnotation) obj_e;
            if (e.parent() != null) {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._annotations_.add(e);
        }
    }

    public PVisibility getVisibility() {
        return this._visibility_;
    }

    public void setVisibility(PVisibility node) {
        if (this._visibility_ != null) {
            this._visibility_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._visibility_ = node;
    }

    public TKwAbstract getKwAbstract() {
        return this._kwAbstract_;
    }

    public void setKwAbstract(TKwAbstract node) {
        if (this._kwAbstract_ != null) {
            this._kwAbstract_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwAbstract_ = node;
    }

    public TKwEvent getKwEvent() {
        return this._kwEvent_;
    }

    public void setKwEvent(TKwEvent node) {
        if (this._kwEvent_ != null) {
            this._kwEvent_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwEvent_ = node;
    }

    public TUidentifier getUidentifier() {
        return this._uidentifier_;
    }

    public void setUidentifier(TUidentifier node) {
        if (this._uidentifier_ != null) {
            this._uidentifier_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._uidentifier_ = node;
    }

    public PSuperClause getSuperClause() {
        return this._superClause_;
    }

    public void setSuperClause(PSuperClause node) {
        if (this._superClause_ != null) {
            this._superClause_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._superClause_ = node;
    }

    public PInsideClause getInsideClause() {
        return this._insideClause_;
    }

    public void setInsideClause(PInsideClause node) {
        if (this._insideClause_ != null) {
            this._insideClause_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._insideClause_ = node;
    }

    public TLBrc getLBrc() {
        return this._lBrc_;
    }

    public void setLBrc(TLBrc node) {
        if (this._lBrc_ != null) {
            this._lBrc_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBrc_ = node;
    }

    public LinkedList<PInnerConceptDecl> getInnerConceptDeclaration() {
        return this._innerConceptDeclaration_;
    }

    public void setInnerConceptDeclaration(List<?> list) {
        for (PInnerConceptDecl e : this._innerConceptDeclaration_) {
            e.parent(null);
        }
        this._innerConceptDeclaration_.clear();

        for (Object obj_e : list) {
            PInnerConceptDecl e = (PInnerConceptDecl) obj_e;
            if (e.parent() != null) {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._innerConceptDeclaration_.add(e);
        }
    }

    public TRBrc getRBrc() {
        return this._rBrc_;
    }

    public void setRBrc(TRBrc node) {
        if (this._rBrc_ != null) {
            this._rBrc_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBrc_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._annotations_)
                + toString(this._visibility_)
                + toString(this._kwAbstract_)
                + toString(this._kwEvent_)
                + toString(this._uidentifier_)
                + toString(this._superClause_)
                + toString(this._insideClause_)
                + toString(this._lBrc_)
                + toString(this._innerConceptDeclaration_)
                + toString(this._rBrc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._annotations_.remove(child)) {
            return;
        }

        if (this._visibility_ == child) {
            this._visibility_ = null;
            return;
        }

        if (this._kwAbstract_ == child) {
            this._kwAbstract_ = null;
            return;
        }

        if (this._kwEvent_ == child) {
            this._kwEvent_ = null;
            return;
        }

        if (this._uidentifier_ == child) {
            this._uidentifier_ = null;
            return;
        }

        if (this._superClause_ == child) {
            this._superClause_ = null;
            return;
        }

        if (this._insideClause_ == child) {
            this._insideClause_ = null;
            return;
        }

        if (this._lBrc_ == child) {
            this._lBrc_ = null;
            return;
        }

        if (this._innerConceptDeclaration_.remove(child)) {
            return;
        }

        if (this._rBrc_ == child) {
            this._rBrc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        for (ListIterator<PAnnotation> i = this._annotations_.listIterator(); i.hasNext(); ) {
            if (i.next() == oldChild) {
                if (newChild != null) {
                    i.set((PAnnotation) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if (this._visibility_ == oldChild) {
            setVisibility((PVisibility) newChild);
            return;
        }

        if (this._kwAbstract_ == oldChild) {
            setKwAbstract((TKwAbstract) newChild);
            return;
        }

        if (this._kwEvent_ == oldChild) {
            setKwEvent((TKwEvent) newChild);
            return;
        }

        if (this._uidentifier_ == oldChild) {
            setUidentifier((TUidentifier) newChild);
            return;
        }

        if (this._superClause_ == oldChild) {
            setSuperClause((PSuperClause) newChild);
            return;
        }

        if (this._insideClause_ == oldChild) {
            setInsideClause((PInsideClause) newChild);
            return;
        }

        if (this._lBrc_ == oldChild) {
            setLBrc((TLBrc) newChild);
            return;
        }

        for (ListIterator<PInnerConceptDecl> i = this._innerConceptDeclaration_.listIterator(); i.hasNext(); ) {
            if (i.next() == oldChild) {
                if (newChild != null) {
                    i.set((PInnerConceptDecl) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if (this._rBrc_ == oldChild) {
            setRBrc((TRBrc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
