/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AExecuteDirective extends PDirective {
    private TExecute _execute_;
    private PPath _path_;

    public AExecuteDirective() {
        // Constructor
    }

    public AExecuteDirective(
            @SuppressWarnings("hiding") TExecute _execute_,
            @SuppressWarnings("hiding") PPath _path_) {
        // Constructor
        setExecute(_execute_);

        setPath(_path_);

    }

    @Override
    public Object clone() {
        return new AExecuteDirective(
                cloneNode(this._execute_),
                cloneNode(this._path_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAExecuteDirective(this);
    }

    public TExecute getExecute() {
        return this._execute_;
    }

    public void setExecute(TExecute node) {
        if (this._execute_ != null) {
            this._execute_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._execute_ = node;
    }

    public PPath getPath() {
        return this._path_;
    }

    public void setPath(PPath node) {
        if (this._path_ != null) {
            this._path_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._path_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._execute_)
                + toString(this._path_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._execute_ == child) {
            this._execute_ = null;
            return;
        }

        if (this._path_ == child) {
            this._path_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._execute_ == oldChild) {
            setExecute((TExecute) newChild);
            return;
        }

        if (this._path_ == oldChild) {
            setPath((PPath) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
