/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AExtendsWildcardBounds extends PWildcardBounds
{
    private TKwExtends _kwExtends_;
    private PReferenceType _referenceType_;

    public AExtendsWildcardBounds()
    {
        // Constructor
    }

    public AExtendsWildcardBounds(
        @SuppressWarnings("hiding") TKwExtends _kwExtends_,
        @SuppressWarnings("hiding") PReferenceType _referenceType_)
    {
        // Constructor
        setKwExtends(_kwExtends_);

        setReferenceType(_referenceType_);

    }

    @Override
    public Object clone()
    {
        return new AExtendsWildcardBounds(
            cloneNode(this._kwExtends_),
            cloneNode(this._referenceType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExtendsWildcardBounds(this);
    }

    public TKwExtends getKwExtends()
    {
        return this._kwExtends_;
    }

    public void setKwExtends(TKwExtends node)
    {
        if(this._kwExtends_ != null)
        {
            this._kwExtends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwExtends_ = node;
    }

    public PReferenceType getReferenceType()
    {
        return this._referenceType_;
    }

    public void setReferenceType(PReferenceType node)
    {
        if(this._referenceType_ != null)
        {
            this._referenceType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._referenceType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwExtends_)
            + toString(this._referenceType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwExtends_ == child)
        {
            this._kwExtends_ = null;
            return;
        }

        if(this._referenceType_ == child)
        {
            this._referenceType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwExtends_ == oldChild)
        {
            setKwExtends((TKwExtends) newChild);
            return;
        }

        if(this._referenceType_ == oldChild)
        {
            setReferenceType((PReferenceType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
