/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AFailureClause extends PFailureClause
{
    private TKwOnfailure _kwOnfailure_;
    private TColon _colon_;
    private PStatement _statement_;

    public AFailureClause()
    {
        // Constructor
    }

    public AFailureClause(
        @SuppressWarnings("hiding") TKwOnfailure _kwOnfailure_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PStatement _statement_)
    {
        // Constructor
        setKwOnfailure(_kwOnfailure_);

        setColon(_colon_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AFailureClause(
            cloneNode(this._kwOnfailure_),
            cloneNode(this._colon_),
            cloneNode(this._statement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFailureClause(this);
    }

    public TKwOnfailure getKwOnfailure()
    {
        return this._kwOnfailure_;
    }

    public void setKwOnfailure(TKwOnfailure node)
    {
        if(this._kwOnfailure_ != null)
        {
            this._kwOnfailure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwOnfailure_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwOnfailure_)
            + toString(this._colon_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwOnfailure_ == child)
        {
            this._kwOnfailure_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwOnfailure_ == oldChild)
        {
            setKwOnfailure((TKwOnfailure) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
