/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AFilePathDirectiveArgument extends PDirectiveArgument
{
    private TMinusF _minusF_;
    private PPath _path_;

    public AFilePathDirectiveArgument()
    {
        // Constructor
    }

    public AFilePathDirectiveArgument(
        @SuppressWarnings("hiding") TMinusF _minusF_,
        @SuppressWarnings("hiding") PPath _path_)
    {
        // Constructor
        setMinusF(_minusF_);

        setPath(_path_);

    }

    @Override
    public Object clone()
    {
        return new AFilePathDirectiveArgument(
            cloneNode(this._minusF_),
            cloneNode(this._path_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFilePathDirectiveArgument(this);
    }

    public TMinusF getMinusF()
    {
        return this._minusF_;
    }

    public void setMinusF(TMinusF node)
    {
        if(this._minusF_ != null)
        {
            this._minusF_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusF_ = node;
    }

    public PPath getPath()
    {
        return this._path_;
    }

    public void setPath(PPath node)
    {
        if(this._path_ != null)
        {
            this._path_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._path_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusF_)
            + toString(this._path_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusF_ == child)
        {
            this._minusF_ = null;
            return;
        }

        if(this._path_ == child)
        {
            this._path_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusF_ == oldChild)
        {
            setMinusF((TMinusF) newChild);
            return;
        }

        if(this._path_ == oldChild)
        {
            setPath((PPath) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
