/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AFloatVersion extends PVersion {
    private TLitFloat _litFloat_;

    public AFloatVersion() {
        // Constructor
    }

    public AFloatVersion(
            @SuppressWarnings("hiding") TLitFloat _litFloat_) {
        // Constructor
        setLitFloat(_litFloat_);

    }

    @Override
    public Object clone() {
        return new AFloatVersion(
                cloneNode(this._litFloat_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAFloatVersion(this);
    }

    public TLitFloat getLitFloat() {
        return this._litFloat_;
    }

    public void setLitFloat(TLitFloat node) {
        if (this._litFloat_ != null) {
            this._litFloat_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litFloat_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._litFloat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._litFloat_ == child) {
            this._litFloat_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._litFloat_ == oldChild) {
            setLitFloat((TLitFloat) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
