/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AFmlActionFmlCommand extends PFmlCommand {
    private PCommandAssign _commandAssign_;
    private PFmlActionExp _fmlActionExp_;

    public AFmlActionFmlCommand() {
        // Constructor
    }

    public AFmlActionFmlCommand(
            @SuppressWarnings("hiding") PCommandAssign _commandAssign_,
            @SuppressWarnings("hiding") PFmlActionExp _fmlActionExp_) {
        // Constructor
        setCommandAssign(_commandAssign_);

        setFmlActionExp(_fmlActionExp_);

    }

    @Override
    public Object clone() {
        return new AFmlActionFmlCommand(
                cloneNode(this._commandAssign_),
                cloneNode(this._fmlActionExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAFmlActionFmlCommand(this);
    }

    public PCommandAssign getCommandAssign() {
        return this._commandAssign_;
    }

    public void setCommandAssign(PCommandAssign node) {
        if (this._commandAssign_ != null) {
            this._commandAssign_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commandAssign_ = node;
    }

    public PFmlActionExp getFmlActionExp() {
        return this._fmlActionExp_;
    }

    public void setFmlActionExp(PFmlActionExp node) {
        if (this._fmlActionExp_ != null) {
            this._fmlActionExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fmlActionExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._commandAssign_)
                + toString(this._fmlActionExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._commandAssign_ == child) {
            this._commandAssign_ = null;
            return;
        }

        if (this._fmlActionExp_ == child) {
            this._fmlActionExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._commandAssign_ == oldChild) {
            setCommandAssign((PCommandAssign) newChild);
            return;
        }

        if (this._fmlActionExp_ == oldChild) {
            setFmlActionExp((PFmlActionExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
