/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AFmlType extends PType
{
    private PTechnologySpecificType _technologySpecificType_;
    private PAtVersion _atVersion_;

    public AFmlType()
    {
        // Constructor
    }

    public AFmlType(
        @SuppressWarnings("hiding") PTechnologySpecificType _technologySpecificType_,
        @SuppressWarnings("hiding") PAtVersion _atVersion_)
    {
        // Constructor
        setTechnologySpecificType(_technologySpecificType_);

        setAtVersion(_atVersion_);

    }

    @Override
    public Object clone()
    {
        return new AFmlType(
            cloneNode(this._technologySpecificType_),
            cloneNode(this._atVersion_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFmlType(this);
    }

    public PTechnologySpecificType getTechnologySpecificType()
    {
        return this._technologySpecificType_;
    }

    public void setTechnologySpecificType(PTechnologySpecificType node)
    {
        if(this._technologySpecificType_ != null)
        {
            this._technologySpecificType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._technologySpecificType_ = node;
    }

    public PAtVersion getAtVersion()
    {
        return this._atVersion_;
    }

    public void setAtVersion(PAtVersion node)
    {
        if(this._atVersion_ != null)
        {
            this._atVersion_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atVersion_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._technologySpecificType_)
            + toString(this._atVersion_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._technologySpecificType_ == child)
        {
            this._technologySpecificType_ = null;
            return;
        }

        if(this._atVersion_ == child)
        {
            this._atVersion_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._technologySpecificType_ == oldChild)
        {
            setTechnologySpecificType((PTechnologySpecificType) newChild);
            return;
        }

        if(this._atVersion_ == oldChild)
        {
            setAtVersion((PAtVersion) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
