/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AFmlBehaviourDecl extends PBehaviourDecl
{
    private final LinkedList<PAnnotation> _annotations_ = new LinkedList<PAnnotation>();
    private PVisibility _visibility_;
    private PType _type_;
    private TLidentifier _name_;
    private TLPar _lPar_;
    private PFormalArgumentsList _formalArgumentsList_;
    private TRPar _rPar_;
    private TKwWith _kwWith_;
    private TUidentifier _behaviour_;
    private PFmlParameters _fmlParameters_;
    private PFlexoBehaviourBody _flexoBehaviourBody_;

    public AFmlBehaviourDecl()
    {
        // Constructor
    }

    public AFmlBehaviourDecl(
        @SuppressWarnings("hiding") List<?> _annotations_,
        @SuppressWarnings("hiding") PVisibility _visibility_,
        @SuppressWarnings("hiding") PType _type_,
        @SuppressWarnings("hiding") TLidentifier _name_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PFormalArgumentsList _formalArgumentsList_,
        @SuppressWarnings("hiding") TRPar _rPar_,
        @SuppressWarnings("hiding") TKwWith _kwWith_,
        @SuppressWarnings("hiding") TUidentifier _behaviour_,
        @SuppressWarnings("hiding") PFmlParameters _fmlParameters_,
        @SuppressWarnings("hiding") PFlexoBehaviourBody _flexoBehaviourBody_)
    {
        // Constructor
        setAnnotations(_annotations_);

        setVisibility(_visibility_);

        setType(_type_);

        setName(_name_);

        setLPar(_lPar_);

        setFormalArgumentsList(_formalArgumentsList_);

        setRPar(_rPar_);

        setKwWith(_kwWith_);

        setBehaviour(_behaviour_);

        setFmlParameters(_fmlParameters_);

        setFlexoBehaviourBody(_flexoBehaviourBody_);

    }

    @Override
    public Object clone()
    {
        return new AFmlBehaviourDecl(
            cloneList(this._annotations_),
            cloneNode(this._visibility_),
            cloneNode(this._type_),
            cloneNode(this._name_),
            cloneNode(this._lPar_),
            cloneNode(this._formalArgumentsList_),
            cloneNode(this._rPar_),
            cloneNode(this._kwWith_),
            cloneNode(this._behaviour_),
            cloneNode(this._fmlParameters_),
            cloneNode(this._flexoBehaviourBody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFmlBehaviourDecl(this);
    }

    public LinkedList<PAnnotation> getAnnotations()
    {
        return this._annotations_;
    }

    public void setAnnotations(List<?> list)
    {
        for(PAnnotation e : this._annotations_)
        {
            e.parent(null);
        }
        this._annotations_.clear();

        for(Object obj_e : list)
        {
            PAnnotation e = (PAnnotation) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._annotations_.add(e);
        }
    }

    public PVisibility getVisibility()
    {
        return this._visibility_;
    }

    public void setVisibility(PVisibility node)
    {
        if(this._visibility_ != null)
        {
            this._visibility_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._visibility_ = node;
    }

    public PType getType()
    {
        return this._type_;
    }

    public void setType(PType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public TLidentifier getName()
    {
        return this._name_;
    }

    public void setName(TLidentifier node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PFormalArgumentsList getFormalArgumentsList()
    {
        return this._formalArgumentsList_;
    }

    public void setFormalArgumentsList(PFormalArgumentsList node)
    {
        if(this._formalArgumentsList_ != null)
        {
            this._formalArgumentsList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formalArgumentsList_ = node;
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    public TKwWith getKwWith()
    {
        return this._kwWith_;
    }

    public void setKwWith(TKwWith node)
    {
        if(this._kwWith_ != null)
        {
            this._kwWith_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwWith_ = node;
    }

    public TUidentifier getBehaviour()
    {
        return this._behaviour_;
    }

    public void setBehaviour(TUidentifier node)
    {
        if(this._behaviour_ != null)
        {
            this._behaviour_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._behaviour_ = node;
    }

    public PFmlParameters getFmlParameters()
    {
        return this._fmlParameters_;
    }

    public void setFmlParameters(PFmlParameters node)
    {
        if(this._fmlParameters_ != null)
        {
            this._fmlParameters_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fmlParameters_ = node;
    }

    public PFlexoBehaviourBody getFlexoBehaviourBody()
    {
        return this._flexoBehaviourBody_;
    }

    public void setFlexoBehaviourBody(PFlexoBehaviourBody node)
    {
        if(this._flexoBehaviourBody_ != null)
        {
            this._flexoBehaviourBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._flexoBehaviourBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._annotations_)
            + toString(this._visibility_)
            + toString(this._type_)
            + toString(this._name_)
            + toString(this._lPar_)
            + toString(this._formalArgumentsList_)
            + toString(this._rPar_)
            + toString(this._kwWith_)
            + toString(this._behaviour_)
            + toString(this._fmlParameters_)
            + toString(this._flexoBehaviourBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._annotations_.remove(child))
        {
            return;
        }

        if(this._visibility_ == child)
        {
            this._visibility_ = null;
            return;
        }

        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._formalArgumentsList_ == child)
        {
            this._formalArgumentsList_ = null;
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        if(this._kwWith_ == child)
        {
            this._kwWith_ = null;
            return;
        }

        if(this._behaviour_ == child)
        {
            this._behaviour_ = null;
            return;
        }

        if(this._fmlParameters_ == child)
        {
            this._fmlParameters_ = null;
            return;
        }

        if(this._flexoBehaviourBody_ == child)
        {
            this._flexoBehaviourBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAnnotation> i = this._annotations_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAnnotation) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._visibility_ == oldChild)
        {
            setVisibility((PVisibility) newChild);
            return;
        }

        if(this._type_ == oldChild)
        {
            setType((PType) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((TLidentifier) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._formalArgumentsList_ == oldChild)
        {
            setFormalArgumentsList((PFormalArgumentsList) newChild);
            return;
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        if(this._kwWith_ == oldChild)
        {
            setKwWith((TKwWith) newChild);
            return;
        }

        if(this._behaviour_ == oldChild)
        {
            setBehaviour((TUidentifier) newChild);
            return;
        }

        if(this._fmlParameters_ == oldChild)
        {
            setFmlParameters((PFmlParameters) newChild);
            return;
        }

        if(this._flexoBehaviourBody_ == oldChild)
        {
            setFlexoBehaviourBody((PFlexoBehaviourBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
