/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AFullQualifiedQualifiedInstance extends PQualifiedInstance {
    private TCidentifier _taId_;
    private TColonColon _colonColon_;
    private TUidentifier _argType_;
    private TColon _colon_;
    private PFmlParameters _fmlParameters_;

    public AFullQualifiedQualifiedInstance() {
        // Constructor
    }

    public AFullQualifiedQualifiedInstance(
            @SuppressWarnings("hiding") TCidentifier _taId_,
            @SuppressWarnings("hiding") TColonColon _colonColon_,
            @SuppressWarnings("hiding") TUidentifier _argType_,
            @SuppressWarnings("hiding") TColon _colon_,
            @SuppressWarnings("hiding") PFmlParameters _fmlParameters_) {
        // Constructor
        setTaId(_taId_);

        setColonColon(_colonColon_);

        setArgType(_argType_);

        setColon(_colon_);

        setFmlParameters(_fmlParameters_);

    }

    @Override
    public Object clone() {
        return new AFullQualifiedQualifiedInstance(
                cloneNode(this._taId_),
                cloneNode(this._colonColon_),
                cloneNode(this._argType_),
                cloneNode(this._colon_),
                cloneNode(this._fmlParameters_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAFullQualifiedQualifiedInstance(this);
    }

    public TCidentifier getTaId() {
        return this._taId_;
    }

    public void setTaId(TCidentifier node) {
        if (this._taId_ != null) {
            this._taId_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._taId_ = node;
    }

    public TColonColon getColonColon() {
        return this._colonColon_;
    }

    public void setColonColon(TColonColon node) {
        if (this._colonColon_ != null) {
            this._colonColon_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colonColon_ = node;
    }

    public TUidentifier getArgType() {
        return this._argType_;
    }

    public void setArgType(TUidentifier node) {
        if (this._argType_ != null) {
            this._argType_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._argType_ = node;
    }

    public TColon getColon() {
        return this._colon_;
    }

    public void setColon(TColon node) {
        if (this._colon_ != null) {
            this._colon_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PFmlParameters getFmlParameters() {
        return this._fmlParameters_;
    }

    public void setFmlParameters(PFmlParameters node) {
        if (this._fmlParameters_ != null) {
            this._fmlParameters_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fmlParameters_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._taId_)
                + toString(this._colonColon_)
                + toString(this._argType_)
                + toString(this._colon_)
                + toString(this._fmlParameters_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._taId_ == child) {
            this._taId_ = null;
            return;
        }

        if (this._colonColon_ == child) {
            this._colonColon_ = null;
            return;
        }

        if (this._argType_ == child) {
            this._argType_ = null;
            return;
        }

        if (this._colon_ == child) {
            this._colon_ = null;
            return;
        }

        if (this._fmlParameters_ == child) {
            this._fmlParameters_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._taId_ == oldChild) {
            setTaId((TCidentifier) newChild);
            return;
        }

        if (this._colonColon_ == oldChild) {
            setColonColon((TColonColon) newChild);
            return;
        }

        if (this._argType_ == oldChild) {
            setArgType((TUidentifier) newChild);
            return;
        }

        if (this._colon_ == oldChild) {
            setColon((TColon) newChild);
            return;
        }

        if (this._fmlParameters_ == oldChild) {
            setFmlParameters((PFmlParameters) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
