/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AInitializerFmlActionVariableDeclarator extends PVariableDeclarator {
    private TLidentifier _lidentifier_;
    private TAssign _assign_;
    private PFmlActionExp _fmlActionExp_;

    public AInitializerFmlActionVariableDeclarator() {
        // Constructor
    }

    public AInitializerFmlActionVariableDeclarator(
            @SuppressWarnings("hiding") TLidentifier _lidentifier_,
            @SuppressWarnings("hiding") TAssign _assign_,
            @SuppressWarnings("hiding") PFmlActionExp _fmlActionExp_) {
        // Constructor
        setLidentifier(_lidentifier_);

        setAssign(_assign_);

        setFmlActionExp(_fmlActionExp_);

    }

    @Override
    public Object clone() {
        return new AInitializerFmlActionVariableDeclarator(
                cloneNode(this._lidentifier_),
                cloneNode(this._assign_),
                cloneNode(this._fmlActionExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAInitializerFmlActionVariableDeclarator(this);
    }

    public TLidentifier getLidentifier() {
        return this._lidentifier_;
    }

    public void setLidentifier(TLidentifier node) {
        if (this._lidentifier_ != null) {
            this._lidentifier_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lidentifier_ = node;
    }

    public TAssign getAssign() {
        return this._assign_;
    }

    public void setAssign(TAssign node) {
        if (this._assign_ != null) {
            this._assign_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assign_ = node;
    }

    public PFmlActionExp getFmlActionExp() {
        return this._fmlActionExp_;
    }

    public void setFmlActionExp(PFmlActionExp node) {
        if (this._fmlActionExp_ != null) {
            this._fmlActionExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fmlActionExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._lidentifier_)
                + toString(this._assign_)
                + toString(this._fmlActionExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._lidentifier_ == child) {
            this._lidentifier_ = null;
            return;
        }

        if (this._assign_ == child) {
            this._assign_ = null;
            return;
        }

        if (this._fmlActionExp_ == child) {
            this._fmlActionExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._lidentifier_ == oldChild) {
            setLidentifier((TLidentifier) newChild);
            return;
        }

        if (this._assign_ == oldChild) {
            setAssign((TAssign) newChild);
            return;
        }

        if (this._fmlActionExp_ == oldChild) {
            setFmlActionExp((PFmlActionExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
