/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AIntegerLiteral extends PLiteral
{
    private TLitInteger _litInteger_;

    public AIntegerLiteral()
    {
        // Constructor
    }

    public AIntegerLiteral(
        @SuppressWarnings("hiding") TLitInteger _litInteger_)
    {
        // Constructor
        setLitInteger(_litInteger_);

    }

    @Override
    public Object clone()
    {
        return new AIntegerLiteral(
            cloneNode(this._litInteger_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntegerLiteral(this);
    }

    public TLitInteger getLitInteger()
    {
        return this._litInteger_;
    }

    public void setLitInteger(TLitInteger node)
    {
        if(this._litInteger_ != null)
        {
            this._litInteger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litInteger_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._litInteger_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._litInteger_ == child)
        {
            this._litInteger_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._litInteger_ == oldChild)
        {
            setLitInteger((TLitInteger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
