/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ALoadDirective extends PDirective {
    private PCommandAssign _commandAssign_;
    private PLoadDirective _loadDirective_;

    public ALoadDirective() {
        // Constructor
    }

    public ALoadDirective(
            @SuppressWarnings("hiding") PCommandAssign _commandAssign_,
            @SuppressWarnings("hiding") PLoadDirective _loadDirective_) {
        // Constructor
        setCommandAssign(_commandAssign_);

        setLoadDirective(_loadDirective_);

    }

    @Override
    public Object clone() {
        return new ALoadDirective(
                cloneNode(this._commandAssign_),
                cloneNode(this._loadDirective_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseALoadDirective(this);
    }

    public PCommandAssign getCommandAssign() {
        return this._commandAssign_;
    }

    public void setCommandAssign(PCommandAssign node) {
        if (this._commandAssign_ != null) {
            this._commandAssign_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commandAssign_ = node;
    }

    public PLoadDirective getLoadDirective() {
        return this._loadDirective_;
    }

    public void setLoadDirective(PLoadDirective node) {
        if (this._loadDirective_ != null) {
            this._loadDirective_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._loadDirective_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._commandAssign_)
                + toString(this._loadDirective_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._commandAssign_ == child) {
            this._commandAssign_ = null;
            return;
        }

        if (this._loadDirective_ == child) {
            this._loadDirective_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._commandAssign_ == oldChild) {
            setCommandAssign((PCommandAssign) newChild);
            return;
        }

        if (this._loadDirective_ == oldChild) {
            setLoadDirective((PLoadDirective) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
