/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ALogActionFmlActionExp extends PFmlActionExp
{
    private TKwLog _kwLog_;
    private PExpression _expression_;

    public ALogActionFmlActionExp()
    {
        // Constructor
    }

    public ALogActionFmlActionExp(
        @SuppressWarnings("hiding") TKwLog _kwLog_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setKwLog(_kwLog_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new ALogActionFmlActionExp(
            cloneNode(this._kwLog_),
            cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogActionFmlActionExp(this);
    }

    public TKwLog getKwLog()
    {
        return this._kwLog_;
    }

    public void setKwLog(TKwLog node)
    {
        if(this._kwLog_ != null)
        {
            this._kwLog_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwLog_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwLog_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwLog_ == child)
        {
            this._kwLog_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwLog_ == oldChild)
        {
            setKwLog((TKwLog) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
