/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ALongPrimitiveType extends PPrimitiveType
{
    private TTyLong _tyLong_;

    public ALongPrimitiveType()
    {
        // Constructor
    }

    public ALongPrimitiveType(
        @SuppressWarnings("hiding") TTyLong _tyLong_)
    {
        // Constructor
        setTyLong(_tyLong_);

    }

    @Override
    public Object clone()
    {
        return new ALongPrimitiveType(
            cloneNode(this._tyLong_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALongPrimitiveType(this);
    }

    public TTyLong getTyLong()
    {
        return this._tyLong_;
    }

    public void setTyLong(TTyLong node)
    {
        if(this._tyLong_ != null)
        {
            this._tyLong_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tyLong_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tyLong_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tyLong_ == child)
        {
            this._tyLong_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tyLong_ == oldChild)
        {
            setTyLong((TTyLong) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
