/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AManyEnumValuesList extends PEnumValuesList {
    private PEnumValuesList _enumValuesList_;
    private TComma _comma_;
    private PEnumValue _enumValue_;

    public AManyEnumValuesList() {
        // Constructor
    }

    public AManyEnumValuesList(
            @SuppressWarnings("hiding") PEnumValuesList _enumValuesList_,
            @SuppressWarnings("hiding") TComma _comma_,
            @SuppressWarnings("hiding") PEnumValue _enumValue_) {
        // Constructor
        setEnumValuesList(_enumValuesList_);

        setComma(_comma_);

        setEnumValue(_enumValue_);

    }

    @Override
    public Object clone() {
        return new AManyEnumValuesList(
                cloneNode(this._enumValuesList_),
                cloneNode(this._comma_),
                cloneNode(this._enumValue_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAManyEnumValuesList(this);
    }

    public PEnumValuesList getEnumValuesList() {
        return this._enumValuesList_;
    }

    public void setEnumValuesList(PEnumValuesList node) {
        if (this._enumValuesList_ != null) {
            this._enumValuesList_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enumValuesList_ = node;
    }

    public TComma getComma() {
        return this._comma_;
    }

    public void setComma(TComma node) {
        if (this._comma_ != null) {
            this._comma_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PEnumValue getEnumValue() {
        return this._enumValue_;
    }

    public void setEnumValue(PEnumValue node) {
        if (this._enumValue_ != null) {
            this._enumValue_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enumValue_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._enumValuesList_)
                + toString(this._comma_)
                + toString(this._enumValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._enumValuesList_ == child) {
            this._enumValuesList_ = null;
            return;
        }

        if (this._comma_ == child) {
            this._comma_ = null;
            return;
        }

        if (this._enumValue_ == child) {
            this._enumValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._enumValuesList_ == oldChild) {
            setEnumValuesList((PEnumValuesList) newChild);
            return;
        }

        if (this._comma_ == oldChild) {
            setComma((TComma) newChild);
            return;
        }

        if (this._enumValue_ == oldChild) {
            setEnumValue((PEnumValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
