/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AManyQualifiedArgumentListInstances extends PQualifiedArgumentListInstances
{
    private PQualifiedArgumentListInstances _qualifiedArgumentListInstances_;
    private TComma _comma_;
    private PQualifiedInstance _qualifiedInstance_;

    public AManyQualifiedArgumentListInstances()
    {
        // Constructor
    }

    public AManyQualifiedArgumentListInstances(
        @SuppressWarnings("hiding") PQualifiedArgumentListInstances _qualifiedArgumentListInstances_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PQualifiedInstance _qualifiedInstance_)
    {
        // Constructor
        setQualifiedArgumentListInstances(_qualifiedArgumentListInstances_);

        setComma(_comma_);

        setQualifiedInstance(_qualifiedInstance_);

    }

    @Override
    public Object clone()
    {
        return new AManyQualifiedArgumentListInstances(
            cloneNode(this._qualifiedArgumentListInstances_),
            cloneNode(this._comma_),
            cloneNode(this._qualifiedInstance_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAManyQualifiedArgumentListInstances(this);
    }

    public PQualifiedArgumentListInstances getQualifiedArgumentListInstances()
    {
        return this._qualifiedArgumentListInstances_;
    }

    public void setQualifiedArgumentListInstances(PQualifiedArgumentListInstances node)
    {
        if(this._qualifiedArgumentListInstances_ != null)
        {
            this._qualifiedArgumentListInstances_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._qualifiedArgumentListInstances_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PQualifiedInstance getQualifiedInstance()
    {
        return this._qualifiedInstance_;
    }

    public void setQualifiedInstance(PQualifiedInstance node)
    {
        if(this._qualifiedInstance_ != null)
        {
            this._qualifiedInstance_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._qualifiedInstance_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._qualifiedArgumentListInstances_)
            + toString(this._comma_)
            + toString(this._qualifiedInstance_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._qualifiedArgumentListInstances_ == child)
        {
            this._qualifiedArgumentListInstances_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._qualifiedInstance_ == child)
        {
            this._qualifiedInstance_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._qualifiedArgumentListInstances_ == oldChild)
        {
            setQualifiedArgumentListInstances((PQualifiedArgumentListInstances) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._qualifiedInstance_ == oldChild)
        {
            setQualifiedInstance((PQualifiedInstance) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
