/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AMatchActionFmlActionExp extends PFmlActionExp
{
    private TKwMatch _kwMatch_;
    private TUidentifier _conceptName_;
    private PInClause _inClause_;
    private PFromClause _fromClause_;
    private PQualifiedWhereClause _qualifiedWhereClause_;
    private PCreateClause _createClause_;

    public AMatchActionFmlActionExp()
    {
        // Constructor
    }

    public AMatchActionFmlActionExp(
        @SuppressWarnings("hiding") TKwMatch _kwMatch_,
        @SuppressWarnings("hiding") TUidentifier _conceptName_,
        @SuppressWarnings("hiding") PInClause _inClause_,
        @SuppressWarnings("hiding") PFromClause _fromClause_,
        @SuppressWarnings("hiding") PQualifiedWhereClause _qualifiedWhereClause_,
        @SuppressWarnings("hiding") PCreateClause _createClause_)
    {
        // Constructor
        setKwMatch(_kwMatch_);

        setConceptName(_conceptName_);

        setInClause(_inClause_);

        setFromClause(_fromClause_);

        setQualifiedWhereClause(_qualifiedWhereClause_);

        setCreateClause(_createClause_);

    }

    @Override
    public Object clone()
    {
        return new AMatchActionFmlActionExp(
            cloneNode(this._kwMatch_),
            cloneNode(this._conceptName_),
            cloneNode(this._inClause_),
            cloneNode(this._fromClause_),
            cloneNode(this._qualifiedWhereClause_),
            cloneNode(this._createClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMatchActionFmlActionExp(this);
    }

    public TKwMatch getKwMatch()
    {
        return this._kwMatch_;
    }

    public void setKwMatch(TKwMatch node)
    {
        if(this._kwMatch_ != null)
        {
            this._kwMatch_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwMatch_ = node;
    }

    public TUidentifier getConceptName()
    {
        return this._conceptName_;
    }

    public void setConceptName(TUidentifier node)
    {
        if(this._conceptName_ != null)
        {
            this._conceptName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conceptName_ = node;
    }

    public PInClause getInClause()
    {
        return this._inClause_;
    }

    public void setInClause(PInClause node)
    {
        if(this._inClause_ != null)
        {
            this._inClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inClause_ = node;
    }

    public PFromClause getFromClause()
    {
        return this._fromClause_;
    }

    public void setFromClause(PFromClause node)
    {
        if(this._fromClause_ != null)
        {
            this._fromClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fromClause_ = node;
    }

    public PQualifiedWhereClause getQualifiedWhereClause()
    {
        return this._qualifiedWhereClause_;
    }

    public void setQualifiedWhereClause(PQualifiedWhereClause node)
    {
        if(this._qualifiedWhereClause_ != null)
        {
            this._qualifiedWhereClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._qualifiedWhereClause_ = node;
    }

    public PCreateClause getCreateClause()
    {
        return this._createClause_;
    }

    public void setCreateClause(PCreateClause node)
    {
        if(this._createClause_ != null)
        {
            this._createClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._createClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwMatch_)
            + toString(this._conceptName_)
            + toString(this._inClause_)
            + toString(this._fromClause_)
            + toString(this._qualifiedWhereClause_)
            + toString(this._createClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwMatch_ == child)
        {
            this._kwMatch_ = null;
            return;
        }

        if(this._conceptName_ == child)
        {
            this._conceptName_ = null;
            return;
        }

        if(this._inClause_ == child)
        {
            this._inClause_ = null;
            return;
        }

        if(this._fromClause_ == child)
        {
            this._fromClause_ = null;
            return;
        }

        if(this._qualifiedWhereClause_ == child)
        {
            this._qualifiedWhereClause_ = null;
            return;
        }

        if(this._createClause_ == child)
        {
            this._createClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwMatch_ == oldChild)
        {
            setKwMatch((TKwMatch) newChild);
            return;
        }

        if(this._conceptName_ == oldChild)
        {
            setConceptName((TUidentifier) newChild);
            return;
        }

        if(this._inClause_ == oldChild)
        {
            setInClause((PInClause) newChild);
            return;
        }

        if(this._fromClause_ == oldChild)
        {
            setFromClause((PFromClause) newChild);
            return;
        }

        if(this._qualifiedWhereClause_ == oldChild)
        {
            setQualifiedWhereClause((PQualifiedWhereClause) newChild);
            return;
        }

        if(this._createClause_ == oldChild)
        {
            setCreateClause((PCreateClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
