/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANamespaceDecl extends PNamespaceDecl {
    private TKwNamespace _kwNamespace_;
    private TLitString _stringLiteral_;
    private TKwAs _kwAs_;
    private PIdentifier _nsId_;
    private TSemi _semi_;

    public ANamespaceDecl() {
        // Constructor
    }

    public ANamespaceDecl(
            @SuppressWarnings("hiding") TKwNamespace _kwNamespace_,
            @SuppressWarnings("hiding") TLitString _stringLiteral_,
            @SuppressWarnings("hiding") TKwAs _kwAs_,
            @SuppressWarnings("hiding") PIdentifier _nsId_,
            @SuppressWarnings("hiding") TSemi _semi_) {
        // Constructor
        setKwNamespace(_kwNamespace_);

        setStringLiteral(_stringLiteral_);

        setKwAs(_kwAs_);

        setNsId(_nsId_);

        setSemi(_semi_);

    }

    @Override
    public Object clone() {
        return new ANamespaceDecl(
                cloneNode(this._kwNamespace_),
                cloneNode(this._stringLiteral_),
                cloneNode(this._kwAs_),
                cloneNode(this._nsId_),
                cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseANamespaceDecl(this);
    }

    public TKwNamespace getKwNamespace() {
        return this._kwNamespace_;
    }

    public void setKwNamespace(TKwNamespace node) {
        if (this._kwNamespace_ != null) {
            this._kwNamespace_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwNamespace_ = node;
    }

    public TLitString getStringLiteral() {
        return this._stringLiteral_;
    }

    public void setStringLiteral(TLitString node) {
        if (this._stringLiteral_ != null) {
            this._stringLiteral_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringLiteral_ = node;
    }

    public TKwAs getKwAs() {
        return this._kwAs_;
    }

    public void setKwAs(TKwAs node) {
        if (this._kwAs_ != null) {
            this._kwAs_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwAs_ = node;
    }

    public PIdentifier getNsId() {
        return this._nsId_;
    }

    public void setNsId(PIdentifier node) {
        if (this._nsId_ != null) {
            this._nsId_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nsId_ = node;
    }

    public TSemi getSemi() {
        return this._semi_;
    }

    public void setSemi(TSemi node) {
        if (this._semi_ != null) {
            this._semi_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._kwNamespace_)
                + toString(this._stringLiteral_)
                + toString(this._kwAs_)
                + toString(this._nsId_)
                + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._kwNamespace_ == child) {
            this._kwNamespace_ = null;
            return;
        }

        if (this._stringLiteral_ == child) {
            this._stringLiteral_ = null;
            return;
        }

        if (this._kwAs_ == child) {
            this._kwAs_ = null;
            return;
        }

        if (this._nsId_ == child) {
            this._nsId_ = null;
            return;
        }

        if (this._semi_ == child) {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._kwNamespace_ == oldChild) {
            setKwNamespace((TKwNamespace) newChild);
            return;
        }

        if (this._stringLiteral_ == oldChild) {
            setStringLiteral((TLitString) newChild);
            return;
        }

        if (this._kwAs_ == oldChild) {
            setKwAs((TKwAs) newChild);
            return;
        }

        if (this._nsId_ == oldChild) {
            setNsId((PIdentifier) newChild);
            return;
        }

        if (this._semi_ == oldChild) {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
