/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANamedUriImportImportDecl extends PImportDecl {
    private TKwImport _kwImport_;
    private PTypeDeclType _type_;
    private PIdentifier _name_;
    private TKwFrom _kwFrom_;
    private PReferenceByUri _object_;
    private TSemi _semi_;

    public ANamedUriImportImportDecl() {
        // Constructor
    }

    public ANamedUriImportImportDecl(
            @SuppressWarnings("hiding") TKwImport _kwImport_,
            @SuppressWarnings("hiding") PTypeDeclType _type_,
            @SuppressWarnings("hiding") PIdentifier _name_,
            @SuppressWarnings("hiding") TKwFrom _kwFrom_,
            @SuppressWarnings("hiding") PReferenceByUri _object_,
            @SuppressWarnings("hiding") TSemi _semi_) {
        // Constructor
        setKwImport(_kwImport_);

        setType(_type_);

        setName(_name_);

        setKwFrom(_kwFrom_);

        setObject(_object_);

        setSemi(_semi_);

    }

    @Override
    public Object clone() {
        return new ANamedUriImportImportDecl(
                cloneNode(this._kwImport_),
                cloneNode(this._type_),
                cloneNode(this._name_),
                cloneNode(this._kwFrom_),
                cloneNode(this._object_),
                cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseANamedUriImportImportDecl(this);
    }

    public TKwImport getKwImport() {
        return this._kwImport_;
    }

    public void setKwImport(TKwImport node) {
        if (this._kwImport_ != null) {
            this._kwImport_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwImport_ = node;
    }

    public PTypeDeclType getType() {
        return this._type_;
    }

    public void setType(PTypeDeclType node) {
        if (this._type_ != null) {
            this._type_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PIdentifier getName() {
        return this._name_;
    }

    public void setName(PIdentifier node) {
        if (this._name_ != null) {
            this._name_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TKwFrom getKwFrom() {
        return this._kwFrom_;
    }

    public void setKwFrom(TKwFrom node) {
        if (this._kwFrom_ != null) {
            this._kwFrom_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwFrom_ = node;
    }

    public PReferenceByUri getObject() {
        return this._object_;
    }

    public void setObject(PReferenceByUri node) {
        if (this._object_ != null) {
            this._object_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._object_ = node;
    }

    public TSemi getSemi() {
        return this._semi_;
    }

    public void setSemi(TSemi node) {
        if (this._semi_ != null) {
            this._semi_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._kwImport_)
                + toString(this._type_)
                + toString(this._name_)
                + toString(this._kwFrom_)
                + toString(this._object_)
                + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._kwImport_ == child) {
            this._kwImport_ = null;
            return;
        }

        if (this._type_ == child) {
            this._type_ = null;
            return;
        }

        if (this._name_ == child) {
            this._name_ = null;
            return;
        }

        if (this._kwFrom_ == child) {
            this._kwFrom_ = null;
            return;
        }

        if (this._object_ == child) {
            this._object_ = null;
            return;
        }

        if (this._semi_ == child) {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._kwImport_ == oldChild) {
            setKwImport((TKwImport) newChild);
            return;
        }

        if (this._type_ == oldChild) {
            setType((PTypeDeclType) newChild);
            return;
        }

        if (this._name_ == oldChild) {
            setName((PIdentifier) newChild);
            return;
        }

        if (this._kwFrom_ == oldChild) {
            setKwFrom((TKwFrom) newChild);
            return;
        }

        if (this._object_ == oldChild) {
            setObject((PReferenceByUri) newChild);
            return;
        }

        if (this._semi_ == oldChild) {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
