/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANeqEqualityExp extends PEqualityExp
{
    private PEqualityExp _equalityExp_;
    private TNeq _neq_;
    private PRelationalExp _relationalExp_;

    public ANeqEqualityExp()
    {
        // Constructor
    }

    public ANeqEqualityExp(
        @SuppressWarnings("hiding") PEqualityExp _equalityExp_,
        @SuppressWarnings("hiding") TNeq _neq_,
        @SuppressWarnings("hiding") PRelationalExp _relationalExp_)
    {
        // Constructor
        setEqualityExp(_equalityExp_);

        setNeq(_neq_);

        setRelationalExp(_relationalExp_);

    }

    @Override
    public Object clone()
    {
        return new ANeqEqualityExp(
            cloneNode(this._equalityExp_),
            cloneNode(this._neq_),
            cloneNode(this._relationalExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeqEqualityExp(this);
    }

    public PEqualityExp getEqualityExp()
    {
        return this._equalityExp_;
    }

    public void setEqualityExp(PEqualityExp node)
    {
        if(this._equalityExp_ != null)
        {
            this._equalityExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExp_ = node;
    }

    public TNeq getNeq()
    {
        return this._neq_;
    }

    public void setNeq(TNeq node)
    {
        if(this._neq_ != null)
        {
            this._neq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._neq_ = node;
    }

    public PRelationalExp getRelationalExp()
    {
        return this._relationalExp_;
    }

    public void setRelationalExp(PRelationalExp node)
    {
        if(this._relationalExp_ != null)
        {
            this._relationalExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._equalityExp_)
            + toString(this._neq_)
            + toString(this._relationalExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._equalityExp_ == child)
        {
            this._equalityExp_ = null;
            return;
        }

        if(this._neq_ == child)
        {
            this._neq_ = null;
            return;
        }

        if(this._relationalExp_ == child)
        {
            this._relationalExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._equalityExp_ == oldChild)
        {
            setEqualityExp((PEqualityExp) newChild);
            return;
        }

        if(this._neq_ == oldChild)
        {
            setNeq((TNeq) newChild);
            return;
        }

        if(this._relationalExp_ == oldChild)
        {
            setRelationalExp((PRelationalExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
