/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANormalAbstractActionClause extends PAbstractActionClause
{
    private PActionClause _actionClause_;

    public ANormalAbstractActionClause()
    {
        // Constructor
    }

    public ANormalAbstractActionClause(
        @SuppressWarnings("hiding") PActionClause _actionClause_)
    {
        // Constructor
        setActionClause(_actionClause_);

    }

    @Override
    public Object clone()
    {
        return new ANormalAbstractActionClause(
            cloneNode(this._actionClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANormalAbstractActionClause(this);
    }

    public PActionClause getActionClause()
    {
        return this._actionClause_;
    }

    public void setActionClause(PActionClause node)
    {
        if(this._actionClause_ != null)
        {
            this._actionClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._actionClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._actionClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._actionClause_ == child)
        {
            this._actionClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._actionClause_ == oldChild)
        {
            setActionClause((PActionClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
