/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANotifyActionFmlActionExp extends PFmlActionExp
{
    private TKwNotify _kwNotify_;
    private PExpression _expression_;
    private PInClause _inClause_;

    public ANotifyActionFmlActionExp()
    {
        // Constructor
    }

    public ANotifyActionFmlActionExp(
        @SuppressWarnings("hiding") TKwNotify _kwNotify_,
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") PInClause _inClause_)
    {
        // Constructor
        setKwNotify(_kwNotify_);

        setExpression(_expression_);

        setInClause(_inClause_);

    }

    @Override
    public Object clone()
    {
        return new ANotifyActionFmlActionExp(
            cloneNode(this._kwNotify_),
            cloneNode(this._expression_),
            cloneNode(this._inClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotifyActionFmlActionExp(this);
    }

    public TKwNotify getKwNotify()
    {
        return this._kwNotify_;
    }

    public void setKwNotify(TKwNotify node)
    {
        if(this._kwNotify_ != null)
        {
            this._kwNotify_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwNotify_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public PInClause getInClause()
    {
        return this._inClause_;
    }

    public void setInClause(PInClause node)
    {
        if(this._inClause_ != null)
        {
            this._inClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwNotify_)
            + toString(this._expression_)
            + toString(this._inClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwNotify_ == child)
        {
            this._kwNotify_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._inClause_ == child)
        {
            this._inClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwNotify_ == oldChild)
        {
            setKwNotify((TKwNotify) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        if(this._inClause_ == oldChild)
        {
            setInClause((PInClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
