/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ANullLiteral extends PLiteral {
    private TLitNull _litNull_;

    public ANullLiteral() {
        // Constructor
    }

    public ANullLiteral(
            @SuppressWarnings("hiding") TLitNull _litNull_) {
        // Constructor
        setLitNull(_litNull_);

    }

    @Override
    public Object clone() {
        return new ANullLiteral(
                cloneNode(this._litNull_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseANullLiteral(this);
    }

    public TLitNull getLitNull() {
        return this._litNull_;
    }

    public void setLitNull(TLitNull node) {
        if (this._litNull_ != null) {
            this._litNull_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litNull_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._litNull_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._litNull_ == child) {
            this._litNull_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._litNull_ == oldChild) {
            setLitNull((TLitNull) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
