/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AObjectEnterDirective extends PEnterDirective {
    private TEnter _enter_;
    private PExpression _expression_;

    public AObjectEnterDirective() {
        // Constructor
    }

    public AObjectEnterDirective(
            @SuppressWarnings("hiding") TEnter _enter_,
            @SuppressWarnings("hiding") PExpression _expression_) {
        // Constructor
        setEnter(_enter_);

        setExpression(_expression_);

    }

    @Override
    public Object clone() {
        return new AObjectEnterDirective(
                cloneNode(this._enter_),
                cloneNode(this._expression_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAObjectEnterDirective(this);
    }

    public TEnter getEnter() {
        return this._enter_;
    }

    public void setEnter(TEnter node) {
        if (this._enter_ != null) {
            this._enter_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enter_ = node;
    }

    public PExpression getExpression() {
        return this._expression_;
    }

    public void setExpression(PExpression node) {
        if (this._expression_ != null) {
            this._expression_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._enter_)
                + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._enter_ == child) {
            this._enter_ = null;
            return;
        }

        if (this._expression_ == child) {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._enter_ == oldChild) {
            setEnter((TEnter) newChild);
            return;
        }

        if (this._expression_ == oldChild) {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
