/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AOneQualifiedArgumentListInstances extends PQualifiedArgumentListInstances {
    private PQualifiedInstance _qualifiedInstance_;

    public AOneQualifiedArgumentListInstances() {
        // Constructor
    }

    public AOneQualifiedArgumentListInstances(
            @SuppressWarnings("hiding") PQualifiedInstance _qualifiedInstance_) {
        // Constructor
        setQualifiedInstance(_qualifiedInstance_);

    }

    @Override
    public Object clone() {
        return new AOneQualifiedArgumentListInstances(
                cloneNode(this._qualifiedInstance_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAOneQualifiedArgumentListInstances(this);
    }

    public PQualifiedInstance getQualifiedInstance() {
        return this._qualifiedInstance_;
    }

    public void setQualifiedInstance(PQualifiedInstance node) {
        if (this._qualifiedInstance_ != null) {
            this._qualifiedInstance_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._qualifiedInstance_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._qualifiedInstance_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._qualifiedInstance_ == child) {
            this._qualifiedInstance_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._qualifiedInstance_ == oldChild) {
            setQualifiedInstance((PQualifiedInstance) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
