/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AOpenDirective extends PDirective
{
    private PCommandAssign _commandAssign_;
    private POpenDirective _openDirective_;

    public AOpenDirective()
    {
        // Constructor
    }

    public AOpenDirective(
        @SuppressWarnings("hiding") PCommandAssign _commandAssign_,
        @SuppressWarnings("hiding") POpenDirective _openDirective_)
    {
        // Constructor
        setCommandAssign(_commandAssign_);

        setOpenDirective(_openDirective_);

    }

    @Override
    public Object clone()
    {
        return new AOpenDirective(
            cloneNode(this._commandAssign_),
            cloneNode(this._openDirective_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpenDirective(this);
    }

    public PCommandAssign getCommandAssign()
    {
        return this._commandAssign_;
    }

    public void setCommandAssign(PCommandAssign node)
    {
        if(this._commandAssign_ != null)
        {
            this._commandAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commandAssign_ = node;
    }

    public POpenDirective getOpenDirective()
    {
        return this._openDirective_;
    }

    public void setOpenDirective(POpenDirective node)
    {
        if(this._openDirective_ != null)
        {
            this._openDirective_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openDirective_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._commandAssign_)
            + toString(this._openDirective_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._commandAssign_ == child)
        {
            this._commandAssign_ = null;
            return;
        }

        if(this._openDirective_ == child)
        {
            this._openDirective_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._commandAssign_ == oldChild)
        {
            setCommandAssign((PCommandAssign) newChild);
            return;
        }

        if(this._openDirective_ == oldChild)
        {
            setOpenDirective((POpenDirective) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
