/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APathEnterDirective extends PEnterDirective
{
    private TEnter _enter_;
    private TMinusF _minusF_;
    private PPath _path_;

    public APathEnterDirective()
    {
        // Constructor
    }

    public APathEnterDirective(
        @SuppressWarnings("hiding") TEnter _enter_,
        @SuppressWarnings("hiding") TMinusF _minusF_,
        @SuppressWarnings("hiding") PPath _path_)
    {
        // Constructor
        setEnter(_enter_);

        setMinusF(_minusF_);

        setPath(_path_);

    }

    @Override
    public Object clone()
    {
        return new APathEnterDirective(
            cloneNode(this._enter_),
            cloneNode(this._minusF_),
            cloneNode(this._path_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPathEnterDirective(this);
    }

    public TEnter getEnter()
    {
        return this._enter_;
    }

    public void setEnter(TEnter node)
    {
        if(this._enter_ != null)
        {
            this._enter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._enter_ = node;
    }

    public TMinusF getMinusF()
    {
        return this._minusF_;
    }

    public void setMinusF(TMinusF node)
    {
        if(this._minusF_ != null)
        {
            this._minusF_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusF_ = node;
    }

    public PPath getPath()
    {
        return this._path_;
    }

    public void setPath(PPath node)
    {
        if(this._path_ != null)
        {
            this._path_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._path_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._enter_)
            + toString(this._minusF_)
            + toString(this._path_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._enter_ == child)
        {
            this._enter_ = null;
            return;
        }

        if(this._minusF_ == child)
        {
            this._minusF_ = null;
            return;
        }

        if(this._path_ == child)
        {
            this._path_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._enter_ == oldChild)
        {
            setEnter((TEnter) newChild);
            return;
        }

        if(this._minusF_ == oldChild)
        {
            setMinusF((TMinusF) newChild);
            return;
        }

        if(this._path_ == oldChild)
        {
            setPath((PPath) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
