/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APathOpenDirective extends POpenDirective
{
    private TOpen _open_;
    private PPath _path_;

    public APathOpenDirective()
    {
        // Constructor
    }

    public APathOpenDirective(
        @SuppressWarnings("hiding") TOpen _open_,
        @SuppressWarnings("hiding") PPath _path_)
    {
        // Constructor
        setOpen(_open_);

        setPath(_path_);

    }

    @Override
    public Object clone()
    {
        return new APathOpenDirective(
            cloneNode(this._open_),
            cloneNode(this._path_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPathOpenDirective(this);
    }

    public TOpen getOpen()
    {
        return this._open_;
    }

    public void setOpen(TOpen node)
    {
        if(this._open_ != null)
        {
            this._open_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._open_ = node;
    }

    public PPath getPath()
    {
        return this._path_;
    }

    public void setPath(PPath node)
    {
        if(this._path_ != null)
        {
            this._path_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._path_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._open_)
            + toString(this._path_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._open_ == child)
        {
            this._open_ = null;
            return;
        }

        if(this._path_ == child)
        {
            this._path_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._open_ == oldChild)
        {
            setOpen((TOpen) newChild);
            return;
        }

        if(this._path_ == oldChild)
        {
            setPath((PPath) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
