/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APlainMoreDirective extends PMoreDirective
{
    private TMore _more_;

    public APlainMoreDirective()
    {
        // Constructor
    }

    public APlainMoreDirective(
        @SuppressWarnings("hiding") TMore _more_)
    {
        // Constructor
        setMore(_more_);

    }

    @Override
    public Object clone()
    {
        return new APlainMoreDirective(
            cloneNode(this._more_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlainMoreDirective(this);
    }

    public TMore getMore()
    {
        return this._more_;
    }

    public void setMore(TMore node)
    {
        if(this._more_ != null)
        {
            this._more_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._more_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._more_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._more_ == child)
        {
            this._more_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._more_ == oldChild)
        {
            setMore((TMore) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
