/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APlusAddExp extends PAddExp
{
    private PAddExp _addExp_;
    private TPlus _plus_;
    private PMultExp _multExp_;

    public APlusAddExp()
    {
        // Constructor
    }

    public APlusAddExp(
        @SuppressWarnings("hiding") PAddExp _addExp_,
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PMultExp _multExp_)
    {
        // Constructor
        setAddExp(_addExp_);

        setPlus(_plus_);

        setMultExp(_multExp_);

    }

    @Override
    public Object clone()
    {
        return new APlusAddExp(
            cloneNode(this._addExp_),
            cloneNode(this._plus_),
            cloneNode(this._multExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlusAddExp(this);
    }

    public PAddExp getAddExp()
    {
        return this._addExp_;
    }

    public void setAddExp(PAddExp node)
    {
        if(this._addExp_ != null)
        {
            this._addExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExp_ = node;
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PMultExp getMultExp()
    {
        return this._multExp_;
    }

    public void setMultExp(PMultExp node)
    {
        if(this._multExp_ != null)
        {
            this._multExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._addExp_)
            + toString(this._plus_)
            + toString(this._multExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._addExp_ == child)
        {
            this._addExp_ = null;
            return;
        }

        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._multExp_ == child)
        {
            this._multExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._addExp_ == oldChild)
        {
            setAddExp((PAddExp) newChild);
            return;
        }

        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._multExp_ == oldChild)
        {
            setMultExp((PMultExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
