/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APlusUnaryExp extends PUnaryExp {
    private TPlus _plus_;
    private PUnaryExp _unaryExp_;

    public APlusUnaryExp() {
        // Constructor
    }

    public APlusUnaryExp(
            @SuppressWarnings("hiding") TPlus _plus_,
            @SuppressWarnings("hiding") PUnaryExp _unaryExp_) {
        // Constructor
        setPlus(_plus_);

        setUnaryExp(_unaryExp_);

    }

    @Override
    public Object clone() {
        return new APlusUnaryExp(
                cloneNode(this._plus_),
                cloneNode(this._unaryExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAPlusUnaryExp(this);
    }

    public TPlus getPlus() {
        return this._plus_;
    }

    public void setPlus(TPlus node) {
        if (this._plus_ != null) {
            this._plus_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PUnaryExp getUnaryExp() {
        return this._unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node) {
        if (this._unaryExp_ != null) {
            this._unaryExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._plus_)
                + toString(this._unaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._plus_ == child) {
            this._plus_ = null;
            return;
        }

        if (this._unaryExp_ == child) {
            this._unaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._plus_ == oldChild) {
            setPlus((TPlus) newChild);
            return;
        }

        if (this._unaryExp_ == oldChild) {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
