/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APostfixUnaryExpNotPlusMinus extends PUnaryExpNotPlusMinus
{
    private PPostfixExp _postfixExp_;

    public APostfixUnaryExpNotPlusMinus()
    {
        // Constructor
    }

    public APostfixUnaryExpNotPlusMinus(
        @SuppressWarnings("hiding") PPostfixExp _postfixExp_)
    {
        // Constructor
        setPostfixExp(_postfixExp_);

    }

    @Override
    public Object clone()
    {
        return new APostfixUnaryExpNotPlusMinus(
            cloneNode(this._postfixExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostfixUnaryExpNotPlusMinus(this);
    }

    public PPostfixExp getPostfixExp()
    {
        return this._postfixExp_;
    }

    public void setPostfixExp(PPostfixExp node)
    {
        if(this._postfixExp_ != null)
        {
            this._postfixExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._postfixExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._postfixExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._postfixExp_ == child)
        {
            this._postfixExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._postfixExp_ == oldChild)
        {
            setPostfixExp((PPostfixExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
