/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APostDecrementStatementExpression extends PStatementExpression
{
    private PPostDecrExp _postDecrExp_;

    public APostDecrementStatementExpression()
    {
        // Constructor
    }

    public APostDecrementStatementExpression(
        @SuppressWarnings("hiding") PPostDecrExp _postDecrExp_)
    {
        // Constructor
        setPostDecrExp(_postDecrExp_);

    }

    @Override
    public Object clone()
    {
        return new APostDecrementStatementExpression(
            cloneNode(this._postDecrExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPostDecrementStatementExpression(this);
    }

    public PPostDecrExp getPostDecrExp()
    {
        return this._postDecrExp_;
    }

    public void setPostDecrExp(PPostDecrExp node)
    {
        if(this._postDecrExp_ != null)
        {
            this._postDecrExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._postDecrExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._postDecrExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._postDecrExp_ == child)
        {
            this._postDecrExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._postDecrExp_ == oldChild)
        {
            setPostDecrExp((PPostDecrExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
