/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APreDecrementUnaryExp extends PUnaryExp
{
    private PPreDecrExp _preDecrExp_;

    public APreDecrementUnaryExp()
    {
        // Constructor
    }

    public APreDecrementUnaryExp(
        @SuppressWarnings("hiding") PPreDecrExp _preDecrExp_)
    {
        // Constructor
        setPreDecrExp(_preDecrExp_);

    }

    @Override
    public Object clone()
    {
        return new APreDecrementUnaryExp(
            cloneNode(this._preDecrExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPreDecrementUnaryExp(this);
    }

    public PPreDecrExp getPreDecrExp()
    {
        return this._preDecrExp_;
    }

    public void setPreDecrExp(PPreDecrExp node)
    {
        if(this._preDecrExp_ != null)
        {
            this._preDecrExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preDecrExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._preDecrExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._preDecrExp_ == child)
        {
            this._preDecrExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._preDecrExp_ == oldChild)
        {
            setPreDecrExp((PPreDecrExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
