/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APreIncrementStatementExpression extends PStatementExpression {
    private PPreIncrExp _preIncrExp_;

    public APreIncrementStatementExpression() {
        // Constructor
    }

    public APreIncrementStatementExpression(
            @SuppressWarnings("hiding") PPreIncrExp _preIncrExp_) {
        // Constructor
        setPreIncrExp(_preIncrExp_);

    }

    @Override
    public Object clone() {
        return new APreIncrementStatementExpression(
                cloneNode(this._preIncrExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAPreIncrementStatementExpression(this);
    }

    public PPreIncrExp getPreIncrExp() {
        return this._preIncrExp_;
    }

    public void setPreIncrExp(PPreIncrExp node) {
        if (this._preIncrExp_ != null) {
            this._preIncrExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preIncrExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._preIncrExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._preIncrExp_ == child) {
            this._preIncrExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._preIncrExp_ == oldChild) {
            setPreIncrExp((PPreIncrExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
