/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APrefixedSimplePath extends PSimplePath {
    private PSimplePathPrefix _prefix_;
    private PSimplePath _simplePath_;

    public APrefixedSimplePath() {
        // Constructor
    }

    public APrefixedSimplePath(
            @SuppressWarnings("hiding") PSimplePathPrefix _prefix_,
            @SuppressWarnings("hiding") PSimplePath _simplePath_) {
        // Constructor
        setPrefix(_prefix_);

        setSimplePath(_simplePath_);

    }

    @Override
    public Object clone() {
        return new APrefixedSimplePath(
                cloneNode(this._prefix_),
                cloneNode(this._simplePath_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAPrefixedSimplePath(this);
    }

    public PSimplePathPrefix getPrefix() {
        return this._prefix_;
    }

    public void setPrefix(PSimplePathPrefix node) {
        if (this._prefix_ != null) {
            this._prefix_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prefix_ = node;
    }

    public PSimplePath getSimplePath() {
        return this._simplePath_;
    }

    public void setSimplePath(PSimplePath node) {
        if (this._simplePath_ != null) {
            this._simplePath_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simplePath_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._prefix_)
                + toString(this._simplePath_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._prefix_ == child) {
            this._prefix_ = null;
            return;
        }

        if (this._simplePath_ == child) {
            this._simplePath_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._prefix_ == oldChild) {
            setPrefix((PSimplePathPrefix) newChild);
            return;
        }

        if (this._simplePath_ == oldChild) {
            setSimplePath((PSimplePath) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
