/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APreciseFmlParametersClause extends PPreciseFmlParametersClause {
    private TKwWith _kwWith_;
    private PFmlParameters _fmlParameters_;

    public APreciseFmlParametersClause() {
        // Constructor
    }

    public APreciseFmlParametersClause(
            @SuppressWarnings("hiding") TKwWith _kwWith_,
            @SuppressWarnings("hiding") PFmlParameters _fmlParameters_) {
        // Constructor
        setKwWith(_kwWith_);

        setFmlParameters(_fmlParameters_);

    }

    @Override
    public Object clone() {
        return new APreciseFmlParametersClause(
                cloneNode(this._kwWith_),
                cloneNode(this._fmlParameters_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAPreciseFmlParametersClause(this);
    }

    public TKwWith getKwWith() {
        return this._kwWith_;
    }

    public void setKwWith(TKwWith node) {
        if (this._kwWith_ != null) {
            this._kwWith_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwWith_ = node;
    }

    public PFmlParameters getFmlParameters() {
        return this._fmlParameters_;
    }

    public void setFmlParameters(PFmlParameters node) {
        if (this._fmlParameters_ != null) {
            this._fmlParameters_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fmlParameters_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._kwWith_)
                + toString(this._fmlParameters_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._kwWith_ == child) {
            this._kwWith_ = null;
            return;
        }

        if (this._fmlParameters_ == child) {
            this._fmlParameters_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._kwWith_ == oldChild) {
            setKwWith((TKwWith) newChild);
            return;
        }

        if (this._fmlParameters_ == oldChild) {
            setFmlParameters((PFmlParameters) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
