/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APrimaryUriExpression extends PUriExpression
{
    private PUriExpressionPrimary _uriExpressionPrimary_;

    public APrimaryUriExpression()
    {
        // Constructor
    }

    public APrimaryUriExpression(
        @SuppressWarnings("hiding") PUriExpressionPrimary _uriExpressionPrimary_)
    {
        // Constructor
        setUriExpressionPrimary(_uriExpressionPrimary_);

    }

    @Override
    public Object clone()
    {
        return new APrimaryUriExpression(
            cloneNode(this._uriExpressionPrimary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrimaryUriExpression(this);
    }

    public PUriExpressionPrimary getUriExpressionPrimary()
    {
        return this._uriExpressionPrimary_;
    }

    public void setUriExpressionPrimary(PUriExpressionPrimary node)
    {
        if(this._uriExpressionPrimary_ != null)
        {
            this._uriExpressionPrimary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._uriExpressionPrimary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._uriExpressionPrimary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._uriExpressionPrimary_ == child)
        {
            this._uriExpressionPrimary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._uriExpressionPrimary_ == oldChild)
        {
            setUriExpressionPrimary((PUriExpressionPrimary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
