/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class APwdDirective extends PDirective {
    private TPwd _pwd_;

    public APwdDirective() {
        // Constructor
    }

    public APwdDirective(
            @SuppressWarnings("hiding") TPwd _pwd_) {
        // Constructor
        setPwd(_pwd_);

    }

    @Override
    public Object clone() {
        return new APwdDirective(
                cloneNode(this._pwd_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAPwdDirective(this);
    }

    public TPwd getPwd() {
        return this._pwd_;
    }

    public void setPwd(TPwd node) {
        if (this._pwd_ != null) {
            this._pwd_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pwd_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._pwd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._pwd_ == child) {
            this._pwd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._pwd_ == oldChild) {
            setPwd((TPwd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
