/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AResourceReferenceByUri extends PReferenceByUri
{
    private TLBkt _lBkt_;
    private PUriExpression _resource_;
    private TRBkt _rBkt_;

    public AResourceReferenceByUri()
    {
        // Constructor
    }

    public AResourceReferenceByUri(
        @SuppressWarnings("hiding") TLBkt _lBkt_,
        @SuppressWarnings("hiding") PUriExpression _resource_,
        @SuppressWarnings("hiding") TRBkt _rBkt_)
    {
        // Constructor
        setLBkt(_lBkt_);

        setResource(_resource_);

        setRBkt(_rBkt_);

    }

    @Override
    public Object clone()
    {
        return new AResourceReferenceByUri(
            cloneNode(this._lBkt_),
            cloneNode(this._resource_),
            cloneNode(this._rBkt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAResourceReferenceByUri(this);
    }

    public TLBkt getLBkt()
    {
        return this._lBkt_;
    }

    public void setLBkt(TLBkt node)
    {
        if(this._lBkt_ != null)
        {
            this._lBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBkt_ = node;
    }

    public PUriExpression getResource()
    {
        return this._resource_;
    }

    public void setResource(PUriExpression node)
    {
        if(this._resource_ != null)
        {
            this._resource_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._resource_ = node;
    }

    public TRBkt getRBkt()
    {
        return this._rBkt_;
    }

    public void setRBkt(TRBkt node)
    {
        if(this._rBkt_ != null)
        {
            this._rBkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lBkt_)
            + toString(this._resource_)
            + toString(this._rBkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lBkt_ == child)
        {
            this._lBkt_ = null;
            return;
        }

        if(this._resource_ == child)
        {
            this._resource_ = null;
            return;
        }

        if(this._rBkt_ == child)
        {
            this._rBkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lBkt_ == oldChild)
        {
            setLBkt((TLBkt) newChild);
            return;
        }

        if(this._resource_ == oldChild)
        {
            setResource((PUriExpression) newChild);
            return;
        }

        if(this._rBkt_ == oldChild)
        {
            setRBkt((TRBkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
