/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AResourceCenterDirectiveArgument extends PDirectiveArgument {
    private TMinusRc _minusRc_;
    private PReferenceByUri _referenceByUri_;

    public AResourceCenterDirectiveArgument() {
        // Constructor
    }

    public AResourceCenterDirectiveArgument(
            @SuppressWarnings("hiding") TMinusRc _minusRc_,
            @SuppressWarnings("hiding") PReferenceByUri _referenceByUri_) {
        // Constructor
        setMinusRc(_minusRc_);

        setReferenceByUri(_referenceByUri_);

    }

    @Override
    public Object clone() {
        return new AResourceCenterDirectiveArgument(
                cloneNode(this._minusRc_),
                cloneNode(this._referenceByUri_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAResourceCenterDirectiveArgument(this);
    }

    public TMinusRc getMinusRc() {
        return this._minusRc_;
    }

    public void setMinusRc(TMinusRc node) {
        if (this._minusRc_ != null) {
            this._minusRc_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusRc_ = node;
    }

    public PReferenceByUri getReferenceByUri() {
        return this._referenceByUri_;
    }

    public void setReferenceByUri(PReferenceByUri node) {
        if (this._referenceByUri_ != null) {
            this._referenceByUri_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._referenceByUri_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._minusRc_)
                + toString(this._referenceByUri_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._minusRc_ == child) {
            this._minusRc_ = null;
            return;
        }

        if (this._referenceByUri_ == child) {
            this._referenceByUri_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._minusRc_ == oldChild) {
            setMinusRc((TMinusRc) newChild);
            return;
        }

        if (this._referenceByUri_ == oldChild) {
            setReferenceByUri((PReferenceByUri) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
