/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AResourcesDirective extends PDirective
{
    private PResourcesDirective _resourcesDirective_;

    public AResourcesDirective()
    {
        // Constructor
    }

    public AResourcesDirective(
        @SuppressWarnings("hiding") PResourcesDirective _resourcesDirective_)
    {
        // Constructor
        setResourcesDirective(_resourcesDirective_);

    }

    @Override
    public Object clone()
    {
        return new AResourcesDirective(
            cloneNode(this._resourcesDirective_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAResourcesDirective(this);
    }

    public PResourcesDirective getResourcesDirective()
    {
        return this._resourcesDirective_;
    }

    public void setResourcesDirective(PResourcesDirective node)
    {
        if(this._resourcesDirective_ != null)
        {
            this._resourcesDirective_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._resourcesDirective_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._resourcesDirective_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._resourcesDirective_ == child)
        {
            this._resourcesDirective_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._resourcesDirective_ == oldChild)
        {
            setResourcesDirective((PResourcesDirective) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
