/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASelectType extends PSelectType {

    public ASelectType() {
        // Constructor
    }

    @Override
    public Object clone() {
        return new ASelectType();
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseASelectType(this);
    }

    @Override
    public String toString() {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
