/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AServicesDirective extends PDirective {
    private TServices _services_;

    public AServicesDirective() {
        // Constructor
    }

    public AServicesDirective(
            @SuppressWarnings("hiding") TServices _services_) {
        // Constructor
        setServices(_services_);

    }

    @Override
    public Object clone() {
        return new AServicesDirective(
                cloneNode(this._services_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAServicesDirective(this);
    }

    public TServices getServices() {
        return this._services_;
    }

    public void setServices(TServices node) {
        if (this._services_ != null) {
            this._services_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._services_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._services_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._services_ == child) {
            this._services_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._services_ == oldChild) {
            setServices((TServices) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
