/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AShortPrimitiveType extends PPrimitiveType {
    private TTyShort _tyShort_;

    public AShortPrimitiveType() {
        // Constructor
    }

    public AShortPrimitiveType(
            @SuppressWarnings("hiding") TTyShort _tyShort_) {
        // Constructor
        setTyShort(_tyShort_);

    }

    @Override
    public Object clone() {
        return new AShortPrimitiveType(
                cloneNode(this._tyShort_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAShortPrimitiveType(this);
    }

    public TTyShort getTyShort() {
        return this._tyShort_;
    }

    public void setTyShort(TTyShort node) {
        if (this._tyShort_ != null) {
            this._tyShort_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tyShort_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._tyShort_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._tyShort_ == child) {
            this._tyShort_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._tyShort_ == oldChild) {
            setTyShort((TTyShort) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
