/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASimpleRelationalExp extends PRelationalExp
{
    private PShiftExp _shiftExp_;

    public ASimpleRelationalExp()
    {
        // Constructor
    }

    public ASimpleRelationalExp(
        @SuppressWarnings("hiding") PShiftExp _shiftExp_)
    {
        // Constructor
        setShiftExp(_shiftExp_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleRelationalExp(
            cloneNode(this._shiftExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleRelationalExp(this);
    }

    public PShiftExp getShiftExp()
    {
        return this._shiftExp_;
    }

    public void setShiftExp(PShiftExp node)
    {
        if(this._shiftExp_ != null)
        {
            this._shiftExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shiftExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._shiftExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._shiftExp_ == child)
        {
            this._shiftExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._shiftExp_ == oldChild)
        {
            setShiftExp((PShiftExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
