/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASimpleAndExp extends PAndExp {
    private PEqualityExp _equalityExp_;

    public ASimpleAndExp() {
        // Constructor
    }

    public ASimpleAndExp(
            @SuppressWarnings("hiding") PEqualityExp _equalityExp_) {
        // Constructor
        setEqualityExp(_equalityExp_);

    }

    @Override
    public Object clone() {
        return new ASimpleAndExp(
                cloneNode(this._equalityExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseASimpleAndExp(this);
    }

    public PEqualityExp getEqualityExp() {
        return this._equalityExp_;
    }

    public void setEqualityExp(PEqualityExp node) {
        if (this._equalityExp_ != null) {
            this._equalityExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equalityExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._equalityExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._equalityExp_ == child) {
            this._equalityExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._equalityExp_ == oldChild) {
            setEqualityExp((PEqualityExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
