/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASlashMultExp extends PMultExp
{
    private PMultExp _multExp_;
    private TSlash _slash_;
    private PUnaryExp _unaryExp_;

    public ASlashMultExp()
    {
        // Constructor
    }

    public ASlashMultExp(
        @SuppressWarnings("hiding") PMultExp _multExp_,
        @SuppressWarnings("hiding") TSlash _slash_,
        @SuppressWarnings("hiding") PUnaryExp _unaryExp_)
    {
        // Constructor
        setMultExp(_multExp_);

        setSlash(_slash_);

        setUnaryExp(_unaryExp_);

    }

    @Override
    public Object clone()
    {
        return new ASlashMultExp(
            cloneNode(this._multExp_),
            cloneNode(this._slash_),
            cloneNode(this._unaryExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASlashMultExp(this);
    }

    public PMultExp getMultExp()
    {
        return this._multExp_;
    }

    public void setMultExp(PMultExp node)
    {
        if(this._multExp_ != null)
        {
            this._multExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multExp_ = node;
    }

    public TSlash getSlash()
    {
        return this._slash_;
    }

    public void setSlash(TSlash node)
    {
        if(this._slash_ != null)
        {
            this._slash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._slash_ = node;
    }

    public PUnaryExp getUnaryExp()
    {
        return this._unaryExp_;
    }

    public void setUnaryExp(PUnaryExp node)
    {
        if(this._unaryExp_ != null)
        {
            this._unaryExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multExp_)
            + toString(this._slash_)
            + toString(this._unaryExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multExp_ == child)
        {
            this._multExp_ = null;
            return;
        }

        if(this._slash_ == child)
        {
            this._slash_ = null;
            return;
        }

        if(this._unaryExp_ == child)
        {
            this._unaryExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multExp_ == oldChild)
        {
            setMultExp((PMultExp) newChild);
            return;
        }

        if(this._slash_ == oldChild)
        {
            setSlash((TSlash) newChild);
            return;
        }

        if(this._unaryExp_ == oldChild)
        {
            setUnaryExp((PUnaryExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
