/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AStringLiteral extends PLiteral {
    private TLitString _litString_;

    public AStringLiteral() {
        // Constructor
    }

    public AStringLiteral(
            @SuppressWarnings("hiding") TLitString _litString_) {
        // Constructor
        setLitString(_litString_);

    }

    @Override
    public Object clone() {
        return new AStringLiteral(
                cloneNode(this._litString_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAStringLiteral(this);
    }

    public TLitString getLitString() {
        return this._litString_;
    }

    public void setLitString(TLitString node) {
        if (this._litString_ != null) {
            this._litString_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litString_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._litString_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._litString_ == child) {
            this._litString_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._litString_ == oldChild) {
            setLitString((TLitString) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
