/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ASuperFieldAccess extends PFieldAccess
{
    private TKwSuper _kwSuper_;
    private TDot _dot_;
    private TLidentifier _lidentifier_;

    public ASuperFieldAccess()
    {
        // Constructor
    }

    public ASuperFieldAccess(
        @SuppressWarnings("hiding") TKwSuper _kwSuper_,
        @SuppressWarnings("hiding") TDot _dot_,
        @SuppressWarnings("hiding") TLidentifier _lidentifier_)
    {
        // Constructor
        setKwSuper(_kwSuper_);

        setDot(_dot_);

        setLidentifier(_lidentifier_);

    }

    @Override
    public Object clone()
    {
        return new ASuperFieldAccess(
            cloneNode(this._kwSuper_),
            cloneNode(this._dot_),
            cloneNode(this._lidentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASuperFieldAccess(this);
    }

    public TKwSuper getKwSuper()
    {
        return this._kwSuper_;
    }

    public void setKwSuper(TKwSuper node)
    {
        if(this._kwSuper_ != null)
        {
            this._kwSuper_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwSuper_ = node;
    }

    public TDot getDot()
    {
        return this._dot_;
    }

    public void setDot(TDot node)
    {
        if(this._dot_ != null)
        {
            this._dot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dot_ = node;
    }

    public TLidentifier getLidentifier()
    {
        return this._lidentifier_;
    }

    public void setLidentifier(TLidentifier node)
    {
        if(this._lidentifier_ != null)
        {
            this._lidentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lidentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwSuper_)
            + toString(this._dot_)
            + toString(this._lidentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwSuper_ == child)
        {
            this._kwSuper_ = null;
            return;
        }

        if(this._dot_ == child)
        {
            this._dot_ = null;
            return;
        }

        if(this._lidentifier_ == child)
        {
            this._lidentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwSuper_ == oldChild)
        {
            setKwSuper((TKwSuper) newChild);
            return;
        }

        if(this._dot_ == oldChild)
        {
            setDot((TDot) newChild);
            return;
        }

        if(this._lidentifier_ == oldChild)
        {
            setLidentifier((TLidentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
