/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ATaResourcesDirective extends PResourcesDirective
{
    private TResources _resources_;
    private PIdentifier _technologyAdapter_;

    public ATaResourcesDirective()
    {
        // Constructor
    }

    public ATaResourcesDirective(
        @SuppressWarnings("hiding") TResources _resources_,
        @SuppressWarnings("hiding") PIdentifier _technologyAdapter_)
    {
        // Constructor
        setResources(_resources_);

        setTechnologyAdapter(_technologyAdapter_);

    }

    @Override
    public Object clone()
    {
        return new ATaResourcesDirective(
            cloneNode(this._resources_),
            cloneNode(this._technologyAdapter_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATaResourcesDirective(this);
    }

    public TResources getResources()
    {
        return this._resources_;
    }

    public void setResources(TResources node)
    {
        if(this._resources_ != null)
        {
            this._resources_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._resources_ = node;
    }

    public PIdentifier getTechnologyAdapter()
    {
        return this._technologyAdapter_;
    }

    public void setTechnologyAdapter(PIdentifier node)
    {
        if(this._technologyAdapter_ != null)
        {
            this._technologyAdapter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._technologyAdapter_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._resources_)
            + toString(this._technologyAdapter_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._resources_ == child)
        {
            this._resources_ = null;
            return;
        }

        if(this._technologyAdapter_ == child)
        {
            this._technologyAdapter_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._resources_ == oldChild)
        {
            setResources((TResources) newChild);
            return;
        }

        if(this._technologyAdapter_ == oldChild)
        {
            setTechnologyAdapter((PIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
