/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class ATrueLiteral extends PLiteral
{
    private TLitTrue _litTrue_;

    public ATrueLiteral()
    {
        // Constructor
    }

    public ATrueLiteral(
        @SuppressWarnings("hiding") TLitTrue _litTrue_)
    {
        // Constructor
        setLitTrue(_litTrue_);

    }

    @Override
    public Object clone()
    {
        return new ATrueLiteral(
            cloneNode(this._litTrue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATrueLiteral(this);
    }

    public TLitTrue getLitTrue()
    {
        return this._litTrue_;
    }

    public void setLitTrue(TLitTrue node)
    {
        if(this._litTrue_ != null)
        {
            this._litTrue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._litTrue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._litTrue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._litTrue_ == child)
        {
            this._litTrue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._litTrue_ == oldChild)
        {
            setLitTrue((TLitTrue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
