/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AUnaryUnaryExp extends PUnaryExp {
    private PUnaryExpNotPlusMinus _unaryExpNotPlusMinus_;

    public AUnaryUnaryExp() {
        // Constructor
    }

    public AUnaryUnaryExp(
            @SuppressWarnings("hiding") PUnaryExpNotPlusMinus _unaryExpNotPlusMinus_) {
        // Constructor
        setUnaryExpNotPlusMinus(_unaryExpNotPlusMinus_);

    }

    @Override
    public Object clone() {
        return new AUnaryUnaryExp(
                cloneNode(this._unaryExpNotPlusMinus_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAUnaryUnaryExp(this);
    }

    public PUnaryExpNotPlusMinus getUnaryExpNotPlusMinus() {
        return this._unaryExpNotPlusMinus_;
    }

    public void setUnaryExpNotPlusMinus(PUnaryExpNotPlusMinus node) {
        if (this._unaryExpNotPlusMinus_ != null) {
            this._unaryExpNotPlusMinus_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryExpNotPlusMinus_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._unaryExpNotPlusMinus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._unaryExpNotPlusMinus_ == child) {
            this._unaryExpNotPlusMinus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._unaryExpNotPlusMinus_ == oldChild) {
            setUnaryExpNotPlusMinus((PUnaryExpNotPlusMinus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
