/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AUseDecl extends PUseDecl
{
    private TKwUse _kwUse_;
    private PCompositeTident _identifier_;
    private TKwAs _kwAs_;
    private TCidentifier _taId_;
    private TSemi _semi_;

    public AUseDecl()
    {
        // Constructor
    }

    public AUseDecl(
        @SuppressWarnings("hiding") TKwUse _kwUse_,
        @SuppressWarnings("hiding") PCompositeTident _identifier_,
        @SuppressWarnings("hiding") TKwAs _kwAs_,
        @SuppressWarnings("hiding") TCidentifier _taId_,
        @SuppressWarnings("hiding") TSemi _semi_)
    {
        // Constructor
        setKwUse(_kwUse_);

        setIdentifier(_identifier_);

        setKwAs(_kwAs_);

        setTaId(_taId_);

        setSemi(_semi_);

    }

    @Override
    public Object clone()
    {
        return new AUseDecl(
            cloneNode(this._kwUse_),
            cloneNode(this._identifier_),
            cloneNode(this._kwAs_),
            cloneNode(this._taId_),
            cloneNode(this._semi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUseDecl(this);
    }

    public TKwUse getKwUse()
    {
        return this._kwUse_;
    }

    public void setKwUse(TKwUse node)
    {
        if(this._kwUse_ != null)
        {
            this._kwUse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwUse_ = node;
    }

    public PCompositeTident getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(PCompositeTident node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public TKwAs getKwAs()
    {
        return this._kwAs_;
    }

    public void setKwAs(TKwAs node)
    {
        if(this._kwAs_ != null)
        {
            this._kwAs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwAs_ = node;
    }

    public TCidentifier getTaId()
    {
        return this._taId_;
    }

    public void setTaId(TCidentifier node)
    {
        if(this._taId_ != null)
        {
            this._taId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._taId_ = node;
    }

    public TSemi getSemi()
    {
        return this._semi_;
    }

    public void setSemi(TSemi node)
    {
        if(this._semi_ != null)
        {
            this._semi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwUse_)
            + toString(this._identifier_)
            + toString(this._kwAs_)
            + toString(this._taId_)
            + toString(this._semi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwUse_ == child)
        {
            this._kwUse_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._kwAs_ == child)
        {
            this._kwAs_ = null;
            return;
        }

        if(this._taId_ == child)
        {
            this._taId_ = null;
            return;
        }

        if(this._semi_ == child)
        {
            this._semi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwUse_ == oldChild)
        {
            setKwUse((TKwUse) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((PCompositeTident) newChild);
            return;
        }

        if(this._kwAs_ == oldChild)
        {
            setKwAs((TKwAs) newChild);
            return;
        }

        if(this._taId_ == oldChild)
        {
            setTaId((TCidentifier) newChild);
            return;
        }

        if(this._semi_ == oldChild)
        {
            setSemi((TSemi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
