/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class AUshrShiftExp extends PShiftExp {
    private PShiftExp _shiftExp_;
    private TUshr _ushr_;
    private PAddExp _addExp_;

    public AUshrShiftExp() {
        // Constructor
    }

    public AUshrShiftExp(
            @SuppressWarnings("hiding") PShiftExp _shiftExp_,
            @SuppressWarnings("hiding") TUshr _ushr_,
            @SuppressWarnings("hiding") PAddExp _addExp_) {
        // Constructor
        setShiftExp(_shiftExp_);

        setUshr(_ushr_);

        setAddExp(_addExp_);

    }

    @Override
    public Object clone() {
        return new AUshrShiftExp(
                cloneNode(this._shiftExp_),
                cloneNode(this._ushr_),
                cloneNode(this._addExp_));
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseAUshrShiftExp(this);
    }

    public PShiftExp getShiftExp() {
        return this._shiftExp_;
    }

    public void setShiftExp(PShiftExp node) {
        if (this._shiftExp_ != null) {
            this._shiftExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._shiftExp_ = node;
    }

    public TUshr getUshr() {
        return this._ushr_;
    }

    public void setUshr(TUshr node) {
        if (this._ushr_ != null) {
            this._ushr_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ushr_ = node;
    }

    public PAddExp getAddExp() {
        return this._addExp_;
    }

    public void setAddExp(PAddExp node) {
        if (this._addExp_ != null) {
            this._addExp_.parent(null);
        }

        if (node != null) {
            if (node.parent() != null) {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExp_ = node;
    }

    @Override
    public String toString() {
        return ""
                + toString(this._shiftExp_)
                + toString(this._ushr_)
                + toString(this._addExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child) {
        // Remove child
        if (this._shiftExp_ == child) {
            this._shiftExp_ = null;
            return;
        }

        if (this._ushr_ == child) {
            this._ushr_ = null;
            return;
        }

        if (this._addExp_ == child) {
            this._addExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild) {
        // Replace child
        if (this._shiftExp_ == oldChild) {
            setShiftExp((PShiftExp) newChild);
            return;
        }

        if (this._ushr_ == oldChild) {
            setUshr((TUshr) newChild);
            return;
        }

        if (this._addExp_ == oldChild) {
            setAddExp((PAddExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
