/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

public abstract class PQualifiedArgumentListInstances extends Node {
    // Empty body
}
