/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TColonColon extends Token
{
    public TColonColon()
    {
        super.setText("::");
    }

    public TColonColon(int line, int pos)
    {
        super.setText("::");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TColonColon(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTColonColon(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TColonColon text.");
    }
}
