/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwBegin extends Token
{
    public TKwBegin()
    {
        super.setText("begin");
    }

    public TKwBegin(int line, int pos)
    {
        super.setText("begin");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwBegin(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwBegin(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwBegin text.");
    }
}
