/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwConcept extends Token
{
    public TKwConcept()
    {
        super.setText("concept");
    }

    public TKwConcept(int line, int pos)
    {
        super.setText("concept");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwConcept(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwConcept(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwConcept text.");
    }
}
