/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwDefault extends Token {
    public TKwDefault() {
        super.setText("default");
    }

    public TKwDefault(int line, int pos) {
        super.setText("default");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone() {
        return new TKwDefault(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseTKwDefault(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text) {
        throw new RuntimeException("Cannot change TKwDefault text.");
    }
}
