/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwGet extends Token {
    public TKwGet() {
        super.setText("get");
    }

    public TKwGet(int line, int pos) {
        super.setText("get");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone() {
        return new TKwGet(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseTKwGet(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text) {
        throw new RuntimeException("Cannot change TKwGet text.");
    }
}
