/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwInstanceof extends Token {
    public TKwInstanceof() {
        super.setText("instanceof");
    }

    public TKwInstanceof(int line, int pos) {
        super.setText("instanceof");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone() {
        return new TKwInstanceof(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseTKwInstanceof(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text) {
        throw new RuntimeException("Cannot change TKwInstanceof text.");
    }
}
