/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwPrivate extends Token
{
    public TKwPrivate()
    {
        super.setText("private");
    }

    public TKwPrivate(int line, int pos)
    {
        super.setText("private");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwPrivate(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwPrivate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwPrivate text.");
    }
}
