/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwSuper extends Token
{
    public TKwSuper()
    {
        super.setText("super");
    }

    public TKwSuper(int line, int pos)
    {
        super.setText("super");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwSuper(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwSuper(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwSuper text.");
    }
}
