/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwTypedef extends Token {
    public TKwTypedef() {
        super.setText("typedef");
    }

    public TKwTypedef(int line, int pos) {
        super.setText("typedef");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone() {
        return new TKwTypedef(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseTKwTypedef(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text) {
        throw new RuntimeException("Cannot change TKwTypedef text.");
    }
}
