/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwUse extends Token
{
    public TKwUse()
    {
        super.setText("use");
    }

    public TKwUse(int line, int pos)
    {
        super.setText("use");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwUse(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwUse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwUse text.");
    }
}
