/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TKwValues extends Token {
    public TKwValues() {
        super.setText("values");
    }

    public TKwValues(int line, int pos) {
        super.setText("values");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone() {
        return new TKwValues(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseTKwValues(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text) {
        throw new RuntimeException("Cannot change TKwValues text.");
    }
}
