/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLitFalse extends Token {
    public TLitFalse() {
        super.setText("false");
    }

    public TLitFalse(int line, int pos) {
        super.setText("false");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone() {
        return new TLitFalse(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseTLitFalse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text) {
        throw new RuntimeException("Cannot change TLitFalse text.");
    }
}
