/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TLs extends Token
{
    public TLs()
    {
        super.setText("ls");
    }

    public TLs(int line, int pos)
    {
        super.setText("ls");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLs(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLs(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLs text.");
    }
}
