/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TServices extends Token {
    public TServices() {
        super.setText("services");
    }

    public TServices(int line, int pos) {
        super.setText("services");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone() {
        return new TServices(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw) {
        ((Analysis) sw).caseTServices(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text) {
        throw new RuntimeException("Cannot change TServices text.");
    }
}
