/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.openflexo.foundation.fml.parser.node;

import org.openflexo.foundation.fml.parser.analysis.Analysis;

@SuppressWarnings("nls")
public final class TTyLong extends Token
{
    public TTyLong()
    {
        super.setText("long");
    }

    public TTyLong(int line, int pos)
    {
        super.setText("long");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTyLong(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTyLong(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTyLong text.");
    }
}
